import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {Attachments} from '../bridge/attachments.mjs';
import {createWorkspace,checkWorkspace} from '../bridge/workspaces.mjs';
import {PassStore} from '../bridge/passes.mjs';
import {PassRunner} from '../bridge/pass-runner.mjs';
import {chatArchived,chatMessages} from '../shared/chat.mjs';
const uuid='12345678-1234-1234-1234-123456789abc';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aw-cli-features-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const project=path.join(root,'project'),home=path.join(root,'home');fs.mkdirSync(project);const store=new PassStore(path.join(home,'passes.json'));const homes={[project]:{characters:[{slot:1},{slot:2}]}};return {root,project,home,store,homes};}
const wait=async(fn)=>{const until=Date.now()+15000;while(!fn()){if(Date.now()>until)throw new Error('Timed out');await new Promise(r=>setTimeout(r,20));}};
function approve(store,homes,input){const old=store.snapshot().proposals.find(p=>p.slot===(input.slot||1));const p=store.propose({slot:1,title:'Test',instruction:'Test instruction',version:old?.version,...input},homes);store.decide({id:p.id,version:p.version,action:'approve',confirmed:true},homes);return p;}
function initGit(project){const git=(...args)=>execFileSync('git',['-C',project,...args],{stdio:'pipe'});git('init');git('config','user.email','qa@example.invalid');git('config','user.name','Isolated QA');fs.writeFileSync(path.join(project,'seed.txt'),'base\n');git('add','.');git('commit','-m','Fixture');return git;}
test('attachments are private, typed, bounded, scoped and tamper checked',t=>{
 const {home,project}=fixture(t),files=new Attachments(path.join(home,'attachments'));
 const item=files.save({project,slot:2,name:'brief.md',data:Buffer.from('Review this file').toString('base64')});assert.equal(item.kind,'text');assert.equal(files.resolve([item.id],project,2)[0].text,'Review this file');assert.throws(()=>files.resolve([item.id],project,1),/another resident/);assert.throws(()=>files.resolve(['../secret'],project,2),/Invalid/);assert.throws(()=>files.save({project,slot:2,name:'not.png',data:Buffer.from('not an image').toString('base64')}),/Use PNG/);assert.throws(()=>files.save({project,slot:2,name:'big.txt',data:Buffer.alloc(256*1024+1,65).toString('base64')}),/Use PNG/);
 const file=files.resolve([item.id],project,2)[0].path;assert.equal(fs.statSync(file).mode&0o777,0o600);fs.writeFileSync(file,'changed');assert.throws(()=>files.resolve([item.id],project,2),/changed/);
});
test('worktrees snapshot committed, modified and untracked source without changing the original',async t=>{
 const {home,project}=fixture(t),git=initGit(project);fs.writeFileSync(path.join(project,'seed.txt'),'human edit\n');fs.writeFileSync(path.join(project,'new.txt'),'untracked');fs.writeFileSync(path.join(project,'.gitignore'),'ignored/\n');fs.mkdirSync(path.join(project,'ignored'));fs.writeFileSync(path.join(project,'ignored','runtime'),'private');const before=git('status','--porcelain');
 const workspace=await createWorkspace(project,path.join(home,'worktrees'),'qa');assert.match(workspace.branch,/^codex\//);assert.equal(fs.readFileSync(path.join(workspace.path,'seed.txt'),'utf8'),'human edit\n');assert.equal(fs.readFileSync(path.join(workspace.path,'new.txt'),'utf8'),'untracked');assert.equal(fs.existsSync(path.join(workspace.path,'ignored')),false);assert.deepEqual(git('status','--porcelain'),before);assert.equal((await checkWorkspace(project,workspace)).path,workspace.path);await assert.rejects(()=>checkWorkspace(project,{path:path.join(home,'wrong')}),/unavailable/);await assert.rejects(()=>createWorkspace(project,path.join(project,'nested'),'bad'),/outside/);
});
test('approved isolation executes in its worktree and follow-ups retain the same workspace',async t=>{
 const {home,project,store,homes}=fixture(t);initGit(project);const cli=path.join(home,'mock-cli');fs.writeFileSync(cli,`#!${process.execPath}\nconst fs=require('fs'),a=process.argv.slice(2);process.stdin.resume();process.stdin.on('end',()=>{fs.writeFileSync('task.txt','agent output');console.log(JSON.stringify({type:'thread.started',thread_id:'${uuid}'}));fs.writeFileSync(a[a.indexOf('--output-last-message')+1],JSON.stringify({summary:'Done',checks:[],limitations:[],next:null}));});`,{mode:0o700});approve(store,homes,{project,isolate:true});const runner=new PassRunner(store,{enabled:true,command:cli});runner.start();t.after(()=>runner.stop());await wait(()=>!runner.busy);let first=store.snapshot().runs[0];assert.equal(first.status,'completed');assert.ok(first.workspace);assert.equal(fs.existsSync(path.join(project,'task.txt')),false);assert.equal(fs.readFileSync(path.join(first.workspace.path,'task.txt'),'utf8'),'agent output');approve(store,homes,{project,resumeSession:uuid});await runner.tick();assert.deepEqual(store.snapshot().runs[1].workspace,first.workspace);
});
test('image flags and bounded text data reach the chosen CLI, not activity events',async t=>{
 const {home,project,store,homes}=fixture(t),files=new Attachments(path.join(home,'attachments'));const text=files.save({project,slot:1,name:'brief.txt',data:Buffer.from('ATTACHED_BRIEF').toString('base64')}),image=files.save({project,slot:1,name:'pixel.png',data:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jV9sAAAAASUVORK5CYII='});const cli=path.join(home,'attach-cli');fs.writeFileSync(cli,`#!${process.execPath}\nconst fs=require('fs'),a=process.argv.slice(2);let p='';process.stdin.on('data',c=>p+=c);process.stdin.on('end',()=>{fs.writeFileSync('received.json',JSON.stringify({a,p}));console.log(JSON.stringify({type:'thread.started',thread_id:'${uuid}'}));fs.writeFileSync(a[a.indexOf('--output-last-message')+1],JSON.stringify({summary:'Read attachments',checks:[],limitations:[],next:null}));});`,{mode:0o700});approve(store,homes,{project,attachments:[text,image]});const runner=new PassRunner(store,{enabled:true,command:cli});runner.start();t.after(()=>runner.stop());await wait(()=>!runner.busy);const received=JSON.parse(fs.readFileSync(path.join(project,'received.json')));assert.ok(received.a.includes('--image'));assert.match(received.p,/ATTACHED_BRIEF/);assert.equal(store.snapshot().runs[0].status,'completed');assert.equal(chatMessages(store.snapshot().runs)[0].attachments.length,2);
});
test('stopping a game-owned run terminates the process group and never reports completion',async t=>{
 const {home,project,store,homes}=fixture(t),cli=path.join(home,'slow-cli');fs.writeFileSync(cli,`#!${process.execPath}\nconst fs=require('fs'),{spawn}=require('child_process');process.stdin.resume();process.stdin.on('end',()=>{const c=spawn(process.execPath,['-e',"process.on('SIGTERM',()=>{});setInterval(()=>{},1000)"],{stdio:'ignore'});fs.writeFileSync('descendant.pid',String(c.pid));console.log(JSON.stringify({type:'thread.started',thread_id:'${uuid}'}));setInterval(()=>{},1000);});`,{mode:0o700});approve(store,homes,{project});const runner=new PassRunner(store,{enabled:true,command:cli});runner.start();t.after(()=>runner.stop());await wait(()=>fs.existsSync(path.join(project,'descendant.pid')));const run=store.snapshot().runs[0];assert.throws(()=>runner.cancel('not-owned'),/not controlled/);runner.cancel(run.id);await wait(()=>!runner.busy);const result=store.snapshot().runs[0];assert.equal(result.status,'cancelled');assert.equal(result.result,null);assert.match(result.error,/Changes already made/);await wait(()=>{try{process.kill(Number(fs.readFileSync(path.join(project,'descendant.pid'))),0);return false;}catch(e){return e.code==='ESRCH';}});
});
test('queued cancellation preserves a reply and archive/restore survive restart scoped to the resident',t=>{
 const {project,store,homes}=fixture(t),p=approve(store,homes,{project});store.cancelQueued(p.id);assert.equal(store.claim(),null);assert.match(chatMessages(store.snapshot().runs)[1].text,/Cancelled before execution/);store.chatSetting({project,slot:1,provider:'codex',thread:uuid,action:'archive'});const settings=new PassStore(store.file).snapshot().chatSettings;assert.equal(chatArchived(settings,project,1,'codex',uuid),true);assert.equal(chatArchived(settings,project,2,'codex',uuid),false);store.chatSetting({project,slot:1,provider:'codex',thread:uuid,action:'restore'});assert.equal(chatArchived(store.snapshot().chatSettings,project,1,'codex',uuid),false);
});
