import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
test('prompt tools API keeps upload and archive ownership, origin and execution boundaries',async t=>{
 const home=await fs.mkdtemp(path.join(os.tmpdir(),'aw-prompt-api-')),project=path.join(home,'project'),id='12345678-1234-1234-1234-123456789abc';await fs.mkdir(project);await fs.writeFile(path.join(home,'households.json'),JSON.stringify({[project]:{project,characters:[{slot:1,name:'Ada',seed:1},{slot:2,name:'Ben',seed:2}]}}));await fs.writeFile(path.join(home,'passes.json'),JSON.stringify({proposals:[],runs:[{id:'recorded',project,slot:1,provider:'codex',conversationSession:id,status:'completed',instruction:'Fixture',result:{summary:'Fixture',checks:[],limitations:[],next:null}}]}));
 const child=spawn(process.execPath,['bridge/server.mjs','--port','0'],{env:{...process.env,AGENT_WORLD_HOME:home,AGENT_WORLD_RUNNER:'0',AGENT_WORLD_CODEX_COMMAND:process.execPath,AGENT_WORLD_CLAUDE_COMMAND:process.execPath},stdio:['ignore','pipe','pipe']});t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(home,{recursive:true,force:true});});
 const base=await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(new Error('API startup timeout')),10000);child.stdout.on('data',c=>{out+=c;const match=out.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0]);}});child.once('exit',()=>{clearTimeout(timer);reject(new Error('API exited'));});});
 const post=(route,body,origin)=>fetch(base+route,{method:'POST',headers:{'content-type':'application/json',...(origin?{origin}:{})},body:JSON.stringify(body)});
 assert.equal((await post('/api/voice',{project,slot:1,action:'start'},'https://bad.invalid')).status,403);assert.equal((await post('/api/voice',{project,slot:1,action:'start'})).status,400);assert.equal((await fetch(base+'/api/voice/stream?id=unknown')).status,403);
 const body={project,slot:2,name:'brief.md',data:Buffer.from('Fixture attachment').toString('base64')};assert.equal((await post('/api/pass-attachment',body,'https://example.invalid')).status,403);const attached=await (await post('/api/pass-attachment',body)).json();assert.equal(attached.result.name,'brief.md');
 const rejected=await post('/api/pass-proposal',{project,slot:1,title:'Test',instruction:'Test',attachments:[attached.result.id]});assert.equal(rejected.status,400);assert.match((await rejected.json()).error,/another resident/);
 assert.equal((await post('/api/pass-chat',{project,slot:2,provider:'codex',thread:id,action:'archive'})).status,400);assert.equal((await post('/api/pass-chat',{project,slot:1,provider:'codex',thread:id,action:'archive'})).status,200);let state=await (await fetch(base+'/api/state')).json();assert.equal(state.passes.chatSettings[0].archived,true);assert.equal(state.passes.proposals.length,0);assert.equal(state.passes.runs.length,1);assert.equal((await post('/api/pass-chat',{project,slot:1,provider:'codex',thread:id,action:'restore'})).status,200);state=await (await fetch(base+'/api/state')).json();assert.equal(state.passes.chatSettings[0].archived,false);
 const invalid=await post('/api/pass-proposal',{project,slot:1,title:'Fixture',instruction:'Fixture',execution:{permission:'danger-full-access'}});assert.equal(invalid.status,400);assert.match((await invalid.json()).error,/Unsupported permission/);assert.equal((await fetch(base+'/api/integrations?'+new URLSearchParams({project:'/unregistered',provider:'codex'}))).status,400);const integrations=await fetch(base+'/api/integrations?'+new URLSearchParams({project,provider:'claude'}),{headers:{origin:'https://example.invalid'}});assert.equal(integrations.status,403);
 assert.equal((await post('/api/pass-cancel',{project,slot:2,id:'recorded'})).status,400);
 const claudeModels=await(await fetch(base+'/api/models?'+new URLSearchParams({project,provider:'claude'}))).json();assert.deepEqual(claudeModels.models.map(m=>m.id),['sonnet','opus','haiku']);assert.equal((await fetch(base+'/api/models?'+new URLSearchParams({project,provider:'claude',threads:id}))).status,400);assert.equal((await post('/api/pass-proposal',{project,slot:1,title:'Fixture',instruction:'Fixture',provider:'claude',model:'gpt-test'})).status,400);const chosen=await(await post('/api/pass-proposal',{project,slot:1,title:'Fixture',instruction:'Fixture',provider:'claude',model:'opus',effort:'high'})).json();assert.equal(chosen.result.model,'opus');assert.equal(chosen.result.effort,'high');assert.equal(chosen.result.status,'proposed');
});

test('app connection API surfaces provider requests and keeps ownership and origin guards',async t=>{
 const home=await fs.mkdtemp(path.join(os.tmpdir(),'aw-app-api-')),project=path.join(home,'project'),cli=path.join(home,'codex');await fs.mkdir(project);await fs.writeFile(path.join(home,'households.json'),JSON.stringify({[project]:{project,characters:[{slot:1,name:'Ada',seed:1}]}}));
 await fs.writeFile(cli,`#!/usr/bin/env node
 let b='',call;process.stdin.on('data',c=>{b+=c;let at;while((at=b.indexOf('\\n'))>=0){const m=JSON.parse(b.slice(0,at));b=b.slice(at+1);const send=x=>process.stdout.write(JSON.stringify(x)+'\\n');if(m.method==='initialize')send({id:m.id,result:{}});if(m.method==='thread/start')send({id:m.id,result:{thread:{id:'fixture'}}});if(m.method==='mcpServer/tool/call'){call=m.id;send({id:0,method:'mcpServer/elicitation/request',params:{threadId:'fixture',serverName:'cua_repl',mode:'form',requestedSchema:{type:'object',properties:{}},message:'Allow fixture?',_meta:{connector_id:'computer-use',tool_name:'get_app_state',tool_params:{app:'fixture.app'},persist:['session','always']}}});}if(!m.method&&m.id===0)send({id:call,result:{content:[{type:'text',text:m.result.action==='accept'?'Window: Fixture, App: Fixture':'Computer Use was not approved'}]}});}});`,{mode:0o700});
 const child=spawn(process.execPath,['bridge/server.mjs','--port','0'],{env:{...process.env,AGENT_WORLD_HOME:home,AGENT_WORLD_RUNNER:'1',AGENT_WORLD_CODEX_COMMAND:cli},stdio:['ignore','pipe','pipe']});t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');await fs.rm(home,{recursive:true,force:true});});
 const base=await new Promise((resolve,reject)=>{let out='';child.stdout.on('data',c=>{out+=c;const m=out.match(/http:\/\/127\.0\.0\.1:\d+/);if(m)resolve(m[0]);});child.on('exit',()=>reject(Error('Server exited')));});
 const post=(body,origin)=>fetch(base+'/api/computer-use',{method:'POST',headers:{'content-type':'application/json',...(origin?{origin}:{})},body:JSON.stringify({project,slot:1,...body})});
 assert.equal((await post({action:'start',app:'Fixture'},'https://bad.invalid')).status,403);assert.equal((await post({action:'start',app:'Fixture',slot:99})).status,400);
 const started=await(await post({action:'start',app:'Fixture'})).json();assert.equal(started.ok,true);let state=started.result;
 for(let i=0;i<50&&state.status!=='approval';i++){await new Promise(r=>setTimeout(r,20));state=(await(await post({action:'read',id:state.id})).json()).result;}
 assert.equal(state.status,'approval');assert.equal((await post({action:'always',id:state.id,approvalId:state.approval.id,slot:2})).status,400);assert.equal((await post({action:'always',id:state.id,approvalId:'stale'})).status,400);
 assert.equal((await post({action:'always',id:state.id,approvalId:state.approval.id})).status,200);
 for(let i=0;i<50&&state.status!=='verified';i++){await new Promise(r=>setTimeout(r,20));state=(await(await post({action:'read',id:state.id})).json()).result;}
 assert.equal(state.status,'verified');const s=await(await fetch(base+'/api/state')).json();assert.equal(s.passes.runs.length,0);assert.equal(s.passes.proposals.length,0);
});
