import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {executionOptions,fixedExecution,defaultExecution} from '../shared/execution.mjs';import {integrationArgs,integrationCatalog,codexPlugins} from '../bridge/integrations.mjs';import {reviewContext} from '../bridge/code-review.mjs';import {PassStore,passResult} from '../bridge/passes.mjs';import {PassRunner} from '../bridge/pass-runner.mjs';
function fixture(t){const home=fs.mkdtempSync(path.join(os.tmpdir(),'aw-execution-')),project=path.join(home,'project');fs.mkdirSync(project);t.after(()=>fs.rmSync(home,{recursive:true,force:true}));return {home,project};}
function init(project){const git=(...a)=>execFileSync('git',['-C',project,...a],{encoding:'utf8',stdio:'pipe'});git('init','-b','main');git('config','user.email','qa@example.invalid');git('config','user.name','Fixture');fs.writeFileSync(path.join(project,'index.js'),'export const answer=42;\n');git('add','.');git('commit','-m','Fixture');return git;}
const uuid='12345678-1234-1234-1234-123456789abc';
const wait=async f=>{const until=Date.now()+12000;while(!f()){if(Date.now()>until)throw new Error('Timed out');await new Promise(r=>setTimeout(r,25));}};
test('execution settings validate provider controls and force review boundaries',()=>{
 assert.throws(()=>executionOptions({permission:'danger-full-access'}),/Unsupported/);assert.throws(()=>executionOptions({web:'cached'},'claude'),/cached/);assert.throws(()=>executionOptions({connections:[{name:'aw_docs',url:'https://secret@example.com/mcp'}]}),/without credentials/);assert.throws(()=>executionOptions({connections:[{name:'bad.key',url:'https://example.com'}]}),/name/);assert.throws(()=>executionOptions({mode:'review',review:{scope:'base',ref:'--bad'}}),/Git reference/);
 const e=executionOptions({mode:'review',permission:'workspace-write',external:'selected',servers:['write'],network:true});assert.equal(e.permission,'read-only');assert.equal(e.external,'off');assert.equal(e.network,false);assert.deepEqual(e.servers,[]);assert.equal(executionOptions({mode:'review'},'claude').shell,false);
});
test('review input includes staged/unstaged/untracked changes and resolves exact branch/commit scope',async t=>{
 const {project}=fixture(t),git=init(project),head=git('rev-parse','HEAD').trim();fs.writeFileSync(path.join(project,'index.js'),'export const answer=0;\n');fs.writeFileSync(path.join(project,'new.js'),'export const extra=true;');const before=git('status','--porcelain');const r=await reviewContext(project,{scope:'changes',ref:''});assert.match(r.diff,/-export const answer=42/);assert.match(r.diff,/Untracked file: new.js/);assert.equal(r.head,head);assert.equal(git('status','--porcelain'),before);const commit=await reviewContext(project,{scope:'commit',ref:head});assert.equal(commit.ref,head);assert.match(commit.diff,/export const answer=42/);const base=await reviewContext(project,{scope:'base',ref:'main'});assert.equal(base.diff,'');await assert.rejects(()=>reviewContext(project,{scope:'commit',ref:'missing'}),/scope/);
});
test('integration selection redacts config data and emits scoped overrides without modifying provider files',async t=>{
 const {home,project}=fixture(t),codexHome=path.join(home,'codex');fs.mkdirSync(codexHome);const config=path.join(codexHome,'config.toml');fs.writeFileSync(config,'[plugins."docs@fixture"]\nenabled = true\n[private]\nsecret="DO_NOT_RETURN"\n');const cli=path.join(home,'inventory');fs.writeFileSync(cli,`#!${process.execPath}\nconsole.log(JSON.stringify([{name:'docs',enabled:true,transport:{secret:'DO_NOT_RETURN'}}]));`,{mode:0o700});const options={command:cli,codexHome};const catalog=await integrationCatalog(project,'codex',options);assert.equal(JSON.stringify(catalog).includes('DO_NOT_RETURN'),false);assert.deepEqual(codexPlugins([config]),[{name:'docs@fixture',enabled:true}]);const before=fs.readFileSync(config,'utf8');const args=await integrationArgs(executionOptions({external:'selected',servers:['docs'],plugins:['docs@fixture'],connections:[{name:'aw_extra',url:'https://example.invalid/mcp',tools:['search']}]}),'codex',project,home,options);assert.ok(args.includes('mcp_servers."docs".enabled=true'));assert.ok(args.includes('plugins."docs@fixture".enabled=true'));assert.ok(args.includes('mcp_servers."aw_extra".enabled_tools=["search"]'));const off=await integrationArgs(executionOptions({external:'off'}),'codex',project,home,options);assert.ok(off.includes('mcp_servers."docs".enabled=false'));assert.ok(off.includes('features.plugins=false'));assert.equal(fs.readFileSync(config,'utf8'),before);await assert.rejects(()=>integrationArgs(executionOptions({external:'selected',servers:['missing']}),'codex',project,home,options),/no longer configured/);await assert.rejects(()=>integrationArgs(executionOptions({external:'off'}),'codex',project,home,{command:'/missing-cli'}),/Cannot enforce/);
});
test('Claude custom MCP config stays private and strict; unknown selections fail',async t=>{
 const {home,project}=fixture(t),claudeRoot=path.join(home,'claude');fs.mkdirSync(claudeRoot);fs.writeFileSync(path.join(claudeRoot,'settings.json'),JSON.stringify({enabledPlugins:{'docs@fixture':true}}));const e=executionOptions({external:'selected',plugins:['docs@fixture'],connections:[{name:'aw_docs',url:'https://example.invalid/mcp'}]},'claude');const args=await integrationArgs(e,'claude',project,home,{claudeRoot});assert.ok(args.includes('--strict-mcp-config'));const file=args[args.indexOf('--mcp-config')+1];assert.equal(fs.statSync(file).mode&0o777,0o600);assert.equal(JSON.parse(fs.readFileSync(file)).mcpServers.aw_docs.type,'http');const settings=JSON.parse(args[args.indexOf('--settings')+1]);assert.equal(settings.enabledPlugins['docs@fixture'],true);
});
test('fixed policy rejects per-message overrides and replaces old queued settings',t=>{
 const {home,project}=fixture(t),store=new PassStore(path.join(home,'passes.json')),homes={[project]:{characters:[{slot:1}]}};
 assert.throws(()=>store.propose({project,slot:1,title:'Review',instruction:'Review',execution:{mode:'review'}},homes),/fixed/);
 assert.throws(()=>fixedExecution({web:'disabled'}),/fixed/);
 const p=store.propose({project,slot:1,title:'Prompt',instruction:'Fixture'},homes);store.decide({id:p.id,version:p.version,action:'approve',confirmed:true},homes);
 const data=JSON.parse(fs.readFileSync(store.file));data.proposals[0].execution={mode:'review',permission:'read-only',web:'disabled',external:'off'};fs.writeFileSync(store.file,JSON.stringify(data));
 const run=new PassStore(store.file).claim();assert.deepEqual(run.execution,defaultExecution('codex'));assert.equal(run.execution.mode,'prompt');assert.equal(run.execution.network,true);
});
test('Codex fixed runner enables shell/network/live search and inherits CLI integrations',async t=>{
 const {home,project}=fixture(t),store=new PassStore(path.join(home,'passes.json')),homes={[project]:{characters:[{slot:1}]}},cli=path.join(home,'mock-cli');
 fs.writeFileSync(cli,`#!${process.execPath}\nconst fs=require('fs'),a=process.argv.slice(2);process.stdin.resume();process.stdin.on('end',()=>{fs.writeFileSync('${path.join(home,'received.json')}',JSON.stringify(a));console.log(JSON.stringify({type:'thread.started',thread_id:'${uuid}'}));fs.writeFileSync(a[a.indexOf('--output-last-message')+1],JSON.stringify({summary:'Mock prompt',checks:[],limitations:[],next:null}));});`,{mode:0o700});
 const p=store.propose({project,slot:1,title:'Prompt',instruction:'Fixture only'},homes);store.decide({id:p.id,version:p.version,action:'approve',confirmed:true},homes);const runner=new PassRunner(store,{enabled:true,command:cli});runner.start();t.after(()=>runner.stop());await wait(()=>!runner.busy);assert.equal(store.snapshot().runs[0].status,'completed');const a=JSON.parse(fs.readFileSync(path.join(home,'received.json')));assert.equal(a[a.indexOf('--sandbox')+1],'workspace-write');for(const v of ['features.shell_tool=true','sandbox_workspace_write.network_access=true','web_search="live"'])assert.ok(a.includes(v),v);assert.equal(a.some(v=>v.startsWith('mcp_servers.')||v.startsWith('plugins.')||v.startsWith('features.apps=')),false);assert.equal(a.includes('--dangerously-bypass-approvals-and-sandbox'),false);
});
test('Claude fixed runner uses configured permissions, web tools and existing MCP/plugins',async t=>{
 const {home,project}=fixture(t),store=new PassStore(path.join(home,'passes.json')),homes={[project]:{characters:[{slot:1}]}},cli=path.join(home,'claude-mock');fs.writeFileSync(cli,`#!${process.execPath}\nconst fs=require('fs'),a=process.argv.slice(2);process.stdin.resume();process.stdin.on('end',()=>{fs.writeFileSync('${path.join(home,'claude-args.json')}',JSON.stringify(a));console.log(JSON.stringify({type:'system',subtype:'init',session_id:'${uuid}'}));console.log(JSON.stringify({type:'result',session_id:'${uuid}',structured_output:{summary:'Mock Claude response',checks:[],limitations:[],next:null}}));});`,{mode:0o700});const p=store.propose({project,slot:1,provider:'claude',title:'Prompt',instruction:'Fixture only'},homes);store.decide({id:p.id,version:p.version,action:'approve',confirmed:true},homes);const runner=new PassRunner(store,{enabled:true,claude:cli});runner.start();t.after(()=>runner.stop());await wait(()=>!runner.busy);assert.equal(store.snapshot().runs[0].status,'completed');const a=JSON.parse(fs.readFileSync(path.join(home,'claude-args.json')));assert.equal(a[a.indexOf('--permission-mode')+1],'dontAsk');assert.equal(a[a.indexOf('--allowedTools')+1],'WebSearch,WebFetch');for(const v of ['--disallowedTools','--tools','--strict-mcp-config','--settings','--dangerously-skip-permissions'])assert.equal(a.includes(v),false,v);
});
