import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {World} from '../bridge/world.mjs';import {projectTeam} from '../shared/team.mjs';import {PassStore,passResult} from '../bridge/passes.mjs';import {validateHandoffs,teamPrompt} from '../bridge/handoffs.mjs';import {chatThreads} from '../shared/chat.mjs';
const thread='11111111-1111-1111-1111-111111111111';
const report=(summary='Recorded result',handoffs=[])=>({summary,checks:['Fixture check'],limitations:[],next:null,handoffs});
const task=(id,role,dependsOn=[])=>({id,role,title:id,instruction:'Scoped '+id,dependsOn});
function setup(t,provider='codex'){const home=fs.mkdtempSync(path.join(os.tmpdir(),'aw-handoff-'));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));const project=fs.realpathSync(home),world=new World();world.ensureStarterTeam(project);const team=projectTeam(world.households[project]),store=new PassStore(path.join(home,'passes.json'));const p=store.propose({project,slot:1,provider,team,title:'Website update',instruction:'Research then update the website'},world.households);store.decide({id:p.id,version:p.version,confirmed:true,action:'approve'},world.households);return {project,world,team,store};}
test('first project gets exactly three assigned residents, idempotently, without inventing sessions or changing names',()=>{const w=new World({households:{'/first':{project:'/first',characters:[{slot:1,name:'Otto',seed:1}]}}});w.ensureStarterTeam('/first');w.ensureStarterTeam('/first');w.ensureStarterTeam('/second');assert.equal(w.households['/first'].characters.length,3);assert.equal(w.households['/first'].characters[0].name,'Otto');assert.deepEqual(projectTeam(w.households['/first']).map(c=>c.role),['assistant','junior_developer','researcher']);assert.equal(w.sessions.size,0);assert.equal(w.households['/second'].starterTeam,undefined);const restored=new World({households:JSON.parse(JSON.stringify(w.households))});assert.equal(projectTeam(restored.households['/first']).length,3);});
test('dependency handoffs route to owned chats, carry evidence and return a final pass to the original exact conversation',t=>{const f=setup(t),root=f.store.claim();f.store.conversation(root.id,thread);f.store.finish(root.id,'completed',report('Delegating',[task('research','researcher'),task('build','junior_developer',['research'])]));let s=f.store.snapshot();assert.equal(s.proposals.filter(p=>p.teamRoot===root.id).length,2);assert.equal(s.proposals[1].slot,3);assert.equal(s.proposals[2].slot,2);assert.equal(s.proposals[1].resumeSession,null);assert.equal(chatThreads(s.runs,f.project,3,[],'codex',[],s.proposals)[0].id,'handoff:'+s.proposals[1].id);assert.equal(chatThreads(s.runs,f.project,2,[],'claude',[],s.proposals).length,0);
 const research=f.store.claim();assert.equal(research.slot,3);f.store.conversation(research.id,'33333333-3333-3333-3333-333333333333');f.store.finish(research.id,'completed',report('Sources inspected'));const build=f.store.claim();assert.equal(build.slot,2);assert.equal(build.teamContext[0].result.summary,'Sources inspected');f.store.conversation(build.id,'22222222-2222-2222-2222-222222222222');f.store.finish(build.id,'completed',report('Website changed and checked'));const summary=f.store.claim();assert.equal(summary.slot,1);assert.equal(summary.resumeSession,thread);assert.equal(summary.teamFinal,true);assert.equal(summary.teamContext.length,2);assert.match(teamPrompt(summary),/may not delegate/);f.store.finish(summary.id,'completed',report('Combined result'));assert.equal(f.store.claim(),null);s=f.store.snapshot();assert.equal(new Set(s.runs.map(r=>r.conversationSession).filter(Boolean)).size,3);});
test('invalid, self, unapproved and looping handoffs never add executable work',t=>{const f=setup(t),root=f.store.claim();f.store.conversation(root.id,thread);assert.throws(()=>f.store.finish(root.id,'completed',report('Self',[task('self','assistant')])),/another assigned resident/);assert.equal(f.store.snapshot().proposals.length,1);assert.throws(()=>validateHandoffs([task('cycle','researcher',['cycle'])]),/Invalid handoff/);assert.throws(()=>passResult(report('bad',[task('unknown','invented')])),/Invalid handoff/);f.store.change(d=>d.runs[0].team=null);assert.throws(()=>f.store.finish(root.id,'completed',report('unauthorized',[task('r','researcher')])),/not authorized/);assert.equal(f.store.snapshot().proposals.length,1);});
test('failed prerequisites pause dependents; reports still return without retrying implementation',t=>{const f=setup(t),root=f.store.claim();f.store.conversation(root.id,thread);f.store.finish(root.id,'completed',report('delegated',[task('r','researcher'),task('d','junior_developer',['r'])]));const r=f.store.claim();f.store.finish(r.id,'failed',null,'Fixture source unavailable');const final=f.store.claim();assert.equal(final.teamFinal,true);assert.equal(final.teamContext[0].status,'failed');assert.equal(final.teamContext[1].status,'paused');assert.equal(f.store.snapshot().runs.some(r=>r.slot===2),false);});
test('Stop cancels the remaining team queue and prevents a final auto pass',t=>{const f=setup(t),root=f.store.claim();f.store.conversation(root.id,thread);f.store.finish(root.id,'completed',report('delegated',[task('r','researcher'),task('d','junior_developer',['r'])]));const p=f.store.snapshot().proposals.find(p=>p.teamRoot===root.id);f.store.stopTeam(p.id);assert.equal(f.store.snapshot().runs.find(r=>r.id===root.id).teamStopped,true);assert.equal(f.store.snapshot().proposals.filter(p=>p.teamRoot===root.id&&p.status==='cancelled').length,2);assert.equal(f.store.claim(),null);});
for(const provider of ['codex','claude'])test(`${provider} runner executes assistant → researcher → developer → original-chat report without live providers`,async t=>{
 const f=setup(t,provider),cli=path.join(f.project,'fixture-cli'),log=path.join(f.project,'calls.jsonl');
 fs.writeFileSync(cli,`#!/usr/bin/env node
const fs=require('fs');let input='';process.stdin.on('data',c=>input+=c);process.stdin.on('end',()=>{const args=process.argv.slice(2);let role=input.match(/assigned responsibility is ([^.]+)\\./)?.[1],final=input.includes('Summarize the recorded teammate reports for the original');const id=role==='Researcher'?'33333333-3333-3333-3333-333333333333':role==='Junior developer'?'22222222-2222-2222-2222-222222222222':'11111111-1111-1111-1111-111111111111';fs.appendFileSync(${JSON.stringify(log)},JSON.stringify({args,input,role,final})+'\\n');const result={summary:final?'Combined verified fixture reports':role+' recorded fixture work',checks:[],limitations:[],next:null,handoffs:role==='Assistant'&&!final?[{id:'research',role:'researcher',title:'Research website',instruction:'Inspect fixture sources',dependsOn:[]},{id:'build',role:'junior_developer',title:'Update website',instruction:'Use research to update fixture',dependsOn:['research']}]:[]};if(${JSON.stringify(provider)}==='claude'){console.log(JSON.stringify({type:'system',subtype:'init',session_id:id,model:'claude-fixture'}));console.log(JSON.stringify({type:'result',session_id:id,is_error:false,structured_output:result}));}else{console.log(JSON.stringify({type:'thread.started',thread_id:id}));fs.writeFileSync(args[args.indexOf('--output-last-message')+1],JSON.stringify(result));}});`,{mode:0o700});
 const {PassRunner}=await import('../bridge/pass-runner.mjs');const runner=new PassRunner(f.store,{enabled:true,command:cli,claude:cli});for(let i=0;i<4;i++)await runner.tick();const s=f.store.snapshot(),calls=fs.readFileSync(log,'utf8').trim().split('\n').map(x=>JSON.parse(x));assert.equal(s.runs.length,4);assert.deepEqual(s.runs.map(r=>r.slot),[1,3,2,1]);assert.ok(s.runs.every(r=>r.status==='completed'));assert.equal(s.runs[3].resumeSession,thread);assert.match(calls[2].input,/Researcher recorded fixture work/);assert.equal(calls[3].final,true);assert.ok(calls[3].args.includes(provider==='claude'?'--resume':'resume'));assert.equal(s.runs[3].result.summary,'Combined verified fixture reports');assert.equal(s.proposals.filter(p=>p.status==='approved').length,0);
});
test('inspected interrupted teammate work is not retried and can return failure to the coordinator',t=>{const f=setup(t),root=f.store.claim();f.store.conversation(root.id,thread);f.store.finish(root.id,'completed',report('delegated',[task('r','researcher')]));const r=f.store.claim();f.store.interrupt();assert.equal(f.store.claim(),null);f.store.resolve({id:r.id,confirmed:true});const final=f.store.claim();assert.equal(final.teamFinal,true);assert.equal(final.teamContext[0].status,'failed');});
test('handoff depth and total budget reject further delegation atomically',t=>{const f=setup(t),root=f.store.claim();f.store.conversation(root.id,thread);f.store.finish(root.id,'completed',report('delegated',[task('r','researcher')]));const r=f.store.claim();f.store.conversation(r.id,'33333333-3333-3333-3333-333333333333');f.store.finish(r.id,'completed',report('delegated further',[task('d','junior_developer')]));const d=f.store.claim();f.store.conversation(d.id,'22222222-2222-2222-2222-222222222222');assert.equal(d.teamDepth,2);assert.throws(()=>f.store.finish(d.id,'completed',report('loop',[task('r','researcher')])),/depth reached/);assert.equal(f.store.snapshot().proposals.filter(p=>p.teamRoot===root.id).length,2);});
test('a request cannot enqueue more than six handoffs even across multiple passes',t=>{const f=setup(t),root=f.store.claim();f.store.conversation(root.id,thread);f.store.change(d=>{for(let i=0;i<6;i++)d.proposals.push({id:'earlier-'+i,teamRoot:root.id,slot:2,status:'completed'});});assert.throws(()=>f.store.finish(root.id,'completed',report('over budget',[task('r','researcher')])),/six-handoff limit/);assert.equal(f.store.snapshot().proposals.length,7);});
