import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { pathToFileURL } from 'node:url';
import { startHomeConstruction, homeBuildState, homeCompletionCost, applyGameplayAction, gameplaySpent, mayorStage, TOWN_HALL } from '../shared/gameplay.mjs';

test('new homes use five-minute persisted construction without restarting existing timers', () => {
  const now=Date.now(), initial={connection:{provider:'codex'},townhall:{readyAt:new Date(now-1).toISOString(),expediteSpent:0}};
  assert.throws(()=>startHomeConstruction({},'/home',now),/Town Hall/);
  const game=startHomeConstruction(initial,'/home',now);
  assert.equal(homeBuildState(game,'/home',now).remainingMs,TOWN_HALL.durationMs);
  assert.equal(startHomeConstruction(game,'/home',now+1000),game);
  assert.equal(homeBuildState(game,'/legacy',now).status,'built');
  assert.equal(homeCompletionCost(game,'/home',now+60001),4);
  assert.equal(mayorStage(game,[{project:'/home'}],[],now),'home_building');
  assert.throws(()=>applyGameplayAction(game,{action:'expedite-home',project:'/home'},4,now),/Not enough gems/);
  const finished=applyGameplayAction(game,{action:'expedite-home',project:'/home',cost:0},5,now);
  assert.equal(homeBuildState(finished,'/home',now).status,'built');
  assert.equal(gameplaySpent(finished),35);
  assert.throws(()=>applyGameplayAction(finished,{action:'expedite-home',project:'/home'},5,now),/not under construction/);
  assert.equal(homeBuildState(game,'/home',now+TOWN_HALL.durationMs).status,'built');
});

test('bridge withholds residents/work until build finishes and persists paid completion',async t=>{
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aw-home-build-')),project=path.join(dir,'project');
  const game={connection:{provider:'codex'},townhall:{readyAt:'2026-01-01T00:00:00Z',expediteSpent:0}};
  fs.mkdirSync(project);
  fs.writeFileSync(path.join(project,'keep.txt'),'Preserved');
  const preload=path.join(dir,'fixture.mjs');
  fs.writeFileSync(preload,`import { LocalProjects } from ${JSON.stringify(pathToFileURL(path.resolve('bridge/local-projects.mjs')).href)}; LocalProjects.prototype.list=async()=>({projects:[{id:'fixture',name:'Fixture',path:${JSON.stringify(project)},rootCount:1}],skipped:0});`);
  fs.writeFileSync(path.join(dir,'gameplay.json'),JSON.stringify(game));
  fs.writeFileSync(path.join(dir,'selected-projects.json'),'[]');
  const child=spawn(process.execPath,['--import',pathToFileURL(preload).href,'bridge/server.mjs','--port','0'],{env:{...process.env,AGENT_WORLD_HOME:dir,CODEX_HOME:path.join(dir,'codex'),AGENT_WORLD_RUNNER:'0'},stdio:['ignore','pipe','pipe']});
  t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');fs.rmSync(dir,{recursive:true,force:true});});
  const base=await new Promise((resolve,reject)=>{let out='';const timer=setTimeout(()=>reject(Error('Startup timeout')),10000);child.stdout.on('data',c=>{out+=c;const m=out.match(/http:\/\/127\.0\.0\.1:\d+/);if(m){clearTimeout(timer);resolve(m[0]);}});child.on('error',e=>{clearTimeout(timer);reject(e);});});
  const post=(route,data)=>fetch(base+route,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});
  const imported=await(await post('/api/codex-projects',{action:'import',id:'fixture'})).json();
  const readyAt=imported.result.home.construction.readyAt;
  assert.equal(Date.parse(readyAt)-Date.parse(imported.result.home.construction.startedAt),TOWN_HALL.durationMs);
  const duplicate=await(await post('/api/codex-projects',{action:'import',id:'fixture'})).json();
  assert.equal(duplicate.result.home.construction.readyAt,readyAt);
  let state=await(await fetch(base+'/api/state')).json();
  assert.equal(state.households[0].characters.length,0);
  assert.equal(state.foundation.agents.length,0);
  assert.equal(state.households[0].construction.readyAt,readyAt);
  const denied=await post('/api/pass-proposal',{project,slot:1,title:'Fixture',instruction:'Do not execute'});
  assert.match((await denied.json()).error,/Finish building/);
  assert.equal((await post('/api/gameplay',{action:'expedite-home',project:'/foreign'})).status,400);
  assert.equal((await post('/api/gameplay',{action:'expedite-home',project})).status,200);
  state=await(await fetch(base+'/api/state')).json();
  assert.equal(state.households[0].characters.length,1);
  assert.equal(state.households[0].characters[0].assignedRole,'personal_assistant');
  assert.equal(state.gameplay.homes[project].expediteSpent,5);
  assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'gameplay.json'))).homes[project].expediteSpent,5);
  assert.equal(state.passes.runs.length,0);
  assert.equal(fs.readFileSync(path.join(project,'keep.txt'),'utf8'),'Preserved');
});
