import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {modelCatalog,observedModel,claudeModelCatalog,validClaudeEffort} from '../bridge/models.mjs';
test('model catalog exposes only model identity and availability metadata',()=>{const v=modelCatalog({data:[{model:'gpt-6.1-sol',displayName:'Sol',isDefault:true,secret:'private'},{model:'--bad'}]});assert.deepEqual(v.models,[{id:'gpt-6.1-sol',name:'Sol',isDefault:true,efforts:[],defaultEffort:null}]);});
test('model catalog keeps only known reasoning efforts',()=>{const v=modelCatalog({data:[{model:'gpt-6.1-sol',displayName:'Sol',supportedReasoningEfforts:[{reasoningEffort:'low',description:'Fast'},{reasoningEffort:'--x'},{reasoningEffort:'ultra',description:'Most'}],defaultReasoningEffort:'low'}]});assert.deepEqual(v.models[0].efforts,[{id:'low',description:'Fast'},{id:'ultra',description:'Most'}]);assert.equal(v.models[0].defaultEffort,'low');});
test('conversation model is read from latest matching turn context, not prompt text',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'aw-model-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const id='11111111-2222-3333-4444-555555555555';fs.mkdirSync(path.join(root,'day'));fs.writeFileSync(path.join(root,'day','rollout-'+id+'.jsonl'),[{type:'turn_context',timestamp:'2026-10-06T01:00:00Z',payload:{model:'gpt-6-sol'}},{type:'message',payload:{model:'fake',text:'secret'}},{type:'turn_context',timestamp:'2026-10-06T02:00:00Z',payload:{model:'gpt-6.1-sol'}}].map(JSON.stringify).join('\n'));assert.deepEqual(observedModel(id,root),{thread:id,model:'gpt-6.1-sol',capturedAt:'2026-10-06T02:00:00Z'});assert.equal(observedModel('../escape',root),null);});

test('Claude catalog distinguishes requested aliases from actual observed models',()=>{const runs=[{project:'/p',provider:'claude',conversationSession:'one',model:'opus',observedModel:'claude-opus-observed'},{project:'/p',provider:'claude',resumeSession:'one',model:'sonnet',status:'running'},{project:'/foreign',provider:'claude',conversationSession:'one',observedModel:'private'}];const c=claudeModelCatalog(runs,'/p',['one']);assert.deepEqual(c.models.map(m=>m.id),['sonnet','opus','haiku']);assert.equal(c.availability,'cli-aliases');assert.deepEqual(c.observed,[{thread:'one',model:'claude-opus-observed',requestedModel:'sonnet',requestedEffort:null}]);});

test('Claude exposes CLI effort requests without claiming actual model effort',()=>{const c=claudeModelCatalog([{project:'/p',provider:'claude',conversationSession:'one',model:'opus',effort:'max'}],'/p',['one']);assert.deepEqual(c.efforts.map(e=>e.id),['low','medium','high','xhigh','max']);assert.equal(c.observed[0].requestedEffort,'max');assert.equal(c.observed[0].model,null);assert.equal(validClaudeEffort('ultra'),false);assert.equal(validClaudeEffort('xhigh'),true);});
