import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Schedules,nextTime,scheduleSpec} from '../bridge/schedules.mjs';import {PassStore} from '../bridge/passes.mjs';
const spec={repeat:'daily',time:'09:00',timeZone:'America/New_York'};
test('calendar schedules retain wall time across daylight savings, skip gaps and avoid fall-back duplicates',()=>{
 assert.equal(nextTime(spec,Date.parse('2026-03-07T15:00:00Z')),'2026-03-08T13:00:00.000Z');
 assert.equal(nextTime({...spec,time:'02:30'},Date.parse('2026-03-08T05:00:00Z')),'2026-03-09T06:30:00.000Z');
 assert.equal(nextTime({...spec,time:'01:30'},Date.parse('2026-11-01T05:30:00Z')),'2026-11-02T06:30:00.000Z');
 assert.equal(nextTime({...spec,repeat:'weekly',weekday:1},Date.parse('2026-10-08T18:00:00Z')),'2026-10-12T13:00:00.000Z');
 assert.equal(nextTime({...spec,repeat:'once',date:'2027-01-20'},Date.parse('2026-10-08T18:00:00Z')),'2027-01-20T14:00:00.000Z');
 assert.throws(()=>nextTime({...spec,repeat:'once',date:'2026-03-08',time:'02:30'},Date.parse('2026-03-01T00:00:00Z')),/valid local time/);
});
function fixture(t){const home=fs.mkdtempSync(path.join(os.tmpdir(),'aw-schedule-'));t.after(()=>fs.rmSync(home,{recursive:true,force:true}));const project=fs.realpathSync(home),store=new PassStore(path.join(home,'passes.json'));let now=Date.parse('2026-10-08T12:00:00Z'),blocked=null;const schedules=new Schedules(store,{now:()=>now,allowed:()=>blocked});return {project,store,schedules,setNow:v=>now=Date.parse(v),block:v=>blocked=v,input:{...spec,project,slot:1,provider:'codex',instruction:'Check project tests',model:'gpt-test',effort:'high',title:'Daily check',confirmed:true,action:'create'}};}
test('due scheduling is atomic, catches up once, persists, retains model and resumes one established conversation',t=>{const f=fixture(t);const item=f.schedules.mutate(f.input,()=>{});f.setNow('2026-10-12T16:00:00Z');f.schedules.tick();f.schedules.tick();assert.equal(f.store.snapshot().proposals.length,1);const p=f.store.snapshot().proposals[0];assert.equal(p.model,'gpt-test');assert.equal(p.effort,'high');assert.equal(p.scheduleId,item.id);assert.equal(p.status,'approved');assert.equal(f.store.snapshot().schedules[0].nextAt,'2026-10-13T13:00:00.000Z');const run=f.store.claim();assert.equal(run.scheduleId,item.id);const thread='12345678-1234-1234-1234-123456789abc';f.store.change(d=>{const r=d.runs[0];r.status='completed';r.conversationSession=thread;d.proposals[0].status='completed';});f.schedules.tick();assert.equal(f.store.snapshot().schedules[0].thread,thread);f.setNow('2026-10-13T14:00:00Z');f.schedules.tick();assert.equal(f.store.snapshot().proposals[1].resumeSession,thread);const restart=new Schedules(new PassStore(f.store.file),{now:()=>Date.parse('2026-10-14T14:00:00Z')});restart.tick();assert.equal(f.store.snapshot().proposals.length,2);});
test('once runs only once; blocked projects wait; failed execution pauses and requires explicit resume',t=>{const f=fixture(t);const item=f.schedules.mutate({...f.input,repeat:'once',date:'2026-10-08'},()=>{});f.setNow('2026-10-08T14:00:00Z');f.block('Project is not in your world.');f.schedules.tick();assert.equal(f.store.snapshot().proposals.length,0);f.block(null);f.schedules.tick();f.schedules.tick();assert.equal(f.store.snapshot().proposals.length,1);assert.equal(f.store.snapshot().schedules[0].nextAt,null);const r=f.store.claim();f.store.finish(r.id,'failed',null,'Fixture failure');f.schedules.tick();const paused=f.store.snapshot().schedules[0];assert.equal(paused.status,'paused');assert.match(paused.message,/failed/);assert.throws(()=>f.schedules.mutate({action:'resume',id:item.id,project:f.project,slot:1,version:paused.version},()=>{}),/Confirm/);});
test('pause cancels queued work, deletion retains runs, updates and actions enforce versions and scoped authorization',t=>{const f=fixture(t);const item=f.schedules.mutate(f.input,()=>{});f.setNow('2026-10-08T14:00:00Z');f.schedules.tick();let current=f.store.snapshot().schedules[0];f.schedules.mutate({action:'pause',project:f.project,slot:1,id:item.id,version:current.version},()=>{});assert.equal(f.store.snapshot().proposals[0].status,'cancelled');current=f.store.snapshot().schedules[0];assert.throws(()=>f.schedules.mutate({action:'delete',project:'/other',slot:1,id:item.id,version:current.version},()=>{}),/changed/);assert.throws(()=>f.schedules.mutate({action:'update',...current,version:current.version-1,confirmed:true},()=>{}),/changed/);assert.throws(()=>f.schedules.mutate({...current,action:'update',confirmed:true,instruction:'Different'},()=>{throw Error('Not authorized');}),/Not authorized/);assert.equal(f.store.snapshot().schedules[0].instruction,item.instruction);f.schedules.mutate({action:'delete',...current},()=>{});assert.equal(f.store.snapshot().schedules.length,0);assert.equal(f.store.snapshot().proposals.length,1);assert.throws(()=>scheduleSpec({...f.input,timeZone:'Fake/Zone'},Date.now()),/time zone/);assert.throws(()=>scheduleSpec({...f.input,time:'08:17'},Date.now()),/15-minute/);assert.throws(()=>f.schedules.mutate({...f.input,thread:'12345678-1234-1234-1234-123456789abc'},()=>{}),/own new conversation/);});
test('scheduled queue creates a separate conversation and resumes it on repeat runs',async t=>{
 const f=fixture(t),thread='22345678-1234-1234-1234-123456789abc';f.store.change(d=>d.runs.push({id:'prior',project:f.project,slot:1,provider:'codex',conversationSession:'12345678-1234-1234-1234-123456789abc',status:'completed'}));
 const cli=path.join(f.project,'fixture-cli');fs.writeFileSync(cli,`#!/usr/bin/env node
const fs=require('fs');const args=process.argv.slice(2);fs.writeFileSync(${JSON.stringify(path.join(f.project,'argv.json'))},JSON.stringify(args));const out=args[args.indexOf('--output-last-message')+1];console.log(JSON.stringify({type:'thread.started',thread_id:${JSON.stringify(thread)}}));process.stdin.resume();process.stdin.on('end',()=>fs.writeFileSync(out,JSON.stringify({summary:'Scheduled fixture completed',checks:[],limitations:[],next:null})));`,{mode:0o700});
 f.schedules.mutate(f.input,()=>{});f.setNow('2026-10-08T14:00:00Z');f.schedules.tick();const {PassRunner}=await import('../bridge/pass-runner.mjs');const runner=new PassRunner(f.store,{enabled:true,command:cli});await runner.tick();const run=f.store.snapshot().runs[1];assert.equal(run.status,'completed');assert.equal(run.conversationSession,thread);assert.equal(run.result.summary,'Scheduled fixture completed');assert.equal(run.instruction,f.input.instruction);const args=JSON.parse(fs.readFileSync(path.join(f.project,'argv.json')));assert.equal(args.includes('resume'),false);assert.equal(args.includes('12345678-1234-1234-1234-123456789abc'),false);f.schedules.tick();f.setNow('2026-10-09T14:00:00Z');f.schedules.tick();assert.equal(f.store.snapshot().proposals[1].resumeSession,thread);await runner.tick();const resumedArgs=JSON.parse(fs.readFileSync(path.join(f.project,'argv.json')));assert.equal(resumedArgs.includes('resume'),true);assert.equal(resumedArgs.includes(thread),true);assert.equal(args.includes('gpt-test'),true);
});
test('legacy future schedules detach from old chats without interrupting dispatched once work or changing approved times',t=>{
 const f=fixture(t),thread='12345678-1234-1234-1234-123456789abc',item=f.schedules.mutate(f.input,()=>{});
 f.store.change(d=>{const s=d.schedules[0];delete s.dedicated;s.thread=thread;s.time='09:07';d.schedules.push({...s,id:'legacy-once',repeat:'once',nextAt:null,lastProposalId:'already-dispatched'});d.proposals.push({id:'already-dispatched',scheduleId:'legacy-once',status:'running'});});
 f.schedules.tick();const [future,running]=f.store.snapshot().schedules;
 assert.equal(future.thread,null);assert.equal(future.dedicated,true);assert.equal(future.time,'09:07');assert.equal(running.thread,thread);assert.equal(running.dedicated,undefined);
 f.store.change(d=>d.proposals[0].status='completed');f.schedules.tick();assert.equal(f.store.snapshot().schedules[1].thread,thread);
});
test('Claude scheduled tasks create their own session, retain provider/model/effort and resume it for repeats',async t=>{
 const f=fixture(t),thread='32345678-1234-1234-1234-123456789abc';
 const cli=path.join(f.project,'claude-fixture');fs.writeFileSync(cli,`#!/usr/bin/env node
const fs=require('fs');fs.writeFileSync(${JSON.stringify(path.join(f.project,'claude-argv.json'))},JSON.stringify(process.argv.slice(2)));process.stdin.resume();process.stdin.on('end',()=>{console.log(JSON.stringify({type:'system',subtype:'init',session_id:${JSON.stringify(thread)},model:'claude-opus-fixture'}));console.log(JSON.stringify({type:'result',session_id:${JSON.stringify(thread)},is_error:false,structured_output:{summary:'Claude scheduled fixture response',checks:[],limitations:[],next:null}}));});`,{mode:0o700});
 const item=f.schedules.mutate({...f.input,provider:'claude',model:'opus',effort:'high'},()=>{});
 assert.throws(()=>f.schedules.mutate({...item,action:'update',provider:'codex',confirmed:true},()=>{}),/keeps its provider/);
 f.setNow('2026-10-08T14:00:00Z');f.schedules.tick();const {PassRunner}=await import('../bridge/pass-runner.mjs');const runner=new PassRunner(f.store,{enabled:true,claude:cli,command:path.join(f.project,'missing-codex')});await runner.tick();
 let args=JSON.parse(fs.readFileSync(path.join(f.project,'claude-argv.json')));assert.equal(args.includes('--resume'),false);assert.equal(args[args.indexOf('--model')+1],'opus');assert.equal(args[args.indexOf('--effort')+1],'high');
 const run=f.store.snapshot().runs[0];assert.equal(run.provider,'claude');assert.equal(run.status,'completed');assert.equal(run.conversationSession,thread);assert.equal(run.result.summary,'Claude scheduled fixture response');assert.equal(run.observedModel,'claude-opus-fixture');
 f.schedules.tick();f.setNow('2026-10-09T14:00:00Z');f.schedules.tick();await runner.tick();args=JSON.parse(fs.readFileSync(path.join(f.project,'claude-argv.json')));assert.equal(args[args.indexOf('--resume')+1],thread);assert.equal(f.store.snapshot().runs[1].provider,'claude');assert.equal(f.store.snapshot().runs[1].status,'completed');
});
