import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {PassThrough,Writable} from 'node:stream';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {VoiceSession} from '../bridge/voice.mjs';import {PassStore} from '../bridge/passes.mjs';import {chatMessages} from '../shared/chat.mjs';
const thread='12345678-1234-1234-1234-123456789abc';
function fixture(t,{error=false}={}){const sent=[];const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>{};child.stdin=new Writable({write(bytes,encoding,done){const m=JSON.parse(bytes);sent.push(m);if(m.id!=null&&m.method)queueMicrotask(()=>child.stdout.write(JSON.stringify(m.method==='thread/realtime/start'&&error?{id:m.id,error:{message:'realtime conversation requires API key auth'}}:{id:m.id,result:m.method.startsWith('thread/')&&!m.method.includes('realtime')?{thread:{id:thread}}:{}})+'\n'));done();}});const transcripts=[];const voice=new VoiceSession({spawnChild:()=>child,onTranscript:(s,m)=>transcripts.push(m),timeoutMs:1000});t.after(()=>voice.stop());return {voice,child,sent,transcripts};}
async function connect(voice){voice.start({project:'/tmp',slot:1,thread});for(let n=0;n<30&&voice.state.status==='connecting';n++)await new Promise(r=>setTimeout(r,1));}
test('voice resumes exact UUID, pins workspace permissions and streams audio without persisting it',async t=>{
 const {voice,child,sent,transcripts}=fixture(t);await connect(voice);assert.equal(voice.state.status,'live');assert.equal(sent.find(m=>m.method==='thread/resume').params.threadId,thread);assert.equal(sent.find(m=>m.method==='thread/resume').params.sandbox,'workspace-write');
 await voice.audio({data:'AAA=',sampleRate:24000,numChannels:1,samplesPerChannel:1});assert.equal(sent.at(-1).params.threadId,thread);
 child.stdout.write(JSON.stringify({method:'thread/realtime/outputAudio/delta',params:{threadId:thread,audio:{data:'AAA=',sampleRate:24000,numChannels:1}}})+'\n');assert.equal(voice.events.at(-1).type,'audio');assert.equal(transcripts.length,0);
 assert.throws(()=>voice.audio({data:'bad!',sampleRate:24000,numChannels:1,samplesPerChannel:1}),/Invalid/);
});
test('account authentication failure is shown honestly and shuts down transport',async t=>{const {voice}=fixture(t,{error:true});await connect(voice);assert.equal(voice.state.status,'error');assert.match(voice.state.message,/API key auth/);assert.equal(voice.child,null);});
test('canonical and flat transcript notifications do not duplicate history; wrong thread is ignored',async t=>{
 const {voice,child,transcripts}=fixture(t);await connect(voice);for(const params of [{threadId:'foreign',role:'user',text:'Secret'},{threadId:thread,role:'user',text:'Actual speech'}])child.stdout.write(JSON.stringify({method:'thread/realtime/transcript/done',params})+'\n');child.stdout.write(JSON.stringify({method:'thread/realtime/item/completed',params:{threadId:thread,item:{id:'item',type:'transcriptSegment',role:'user',text:'Actual speech'}}})+'\n');assert.equal(transcripts.length,1);assert.equal(transcripts[0].text,'Actual speech');
});
test('execution approvals wait for human decision and stale approval IDs fail',async t=>{
 const {voice,child,sent}=fixture(t);await connect(voice);child.stdout.write(JSON.stringify({id:400,method:'item/commandExecution/requestApproval',params:{threadId:thread,command:'npm test',reason:'Needs permission'}})+'\n');assert.equal(voice.state.status,'approval');assert.equal(sent.some(m=>m.id===400),false);assert.throws(()=>voice.decide('stale',true),/no longer/);voice.decide(voice.state.approval.id,false);assert.deepEqual(sent.at(-1),{id:400,result:{decision:'decline'}});
});
test('stopping rejects pending permissions and interrupts this voice thread only',async t=>{
 const {voice,sent}=fixture(t);await connect(voice);voice.turn='turn';await voice.stop();assert.equal(voice.state.status,'ended');assert.equal(sent.find(m=>m.method==='turn/interrupt').params.threadId,thread);assert.equal(voice.child,null);
});
test('voice records only returned text in owned chat and blocks simultaneous runner claims',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'aw-voice-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const store=new PassStore(path.join(dir,'passes.json'));const run=store.voiceStart({project:dir,slot:1,thread});store.voiceTranscript(run.id,{id:'one',role:'user',text:'Real transcript'});store.voiceTranscript(run.id,{id:'two',role:'assistant',text:'Actual reply'});assert.equal(store.claim(),null);assert.throws(()=>store.voiceStart({project:dir,slot:2,thread}),/belong/);store.voiceFinish(run.id,{status:'ended',message:'Ended'});assert.deepEqual(chatMessages(store.snapshot().runs).map(m=>m.text),['Real transcript','Actual reply']);assert.equal(store.snapshot().runs[0].status,'cancelled');
});

test('canonical transcript deltas stream while speech is still in progress',async t=>{const {voice,child}=fixture(t);await connect(voice);for(const [method,params] of [['thread/realtime/item/started',{item:{id:'speech',type:'transcriptSegment',role:'assistant',text:''}}],['thread/realtime/item/transcript/delta',{itemId:'speech',delta:'Live words'}]])child.stdout.write(JSON.stringify({method,params:{threadId:thread,...params}})+'\n');assert.deepEqual(voice.events.at(-1).text,'Live words');assert.equal(voice.events.at(-1).done,false);});
