// Simulation activity definitions. buildingIds are compatible venue templates, never evidence of real work.
export const ACTIVITIES = [
  {"id": "eat_a_favorite_meal", "label": "Eat a Favorite Meal", "category": "food", "buildingIds": ["home", "restaurant"]},
  {"id": "eat_ice_cream", "label": "Eat Ice Cream", "category": "food", "buildingIds": ["ice_cream_shop"]},
  {"id": "enjoy_candy_or_chocolate", "label": "Enjoy Candy or Chocolate", "category": "food", "buildingIds": ["home"]},
  {"id": "order_takeout", "label": "Order Takeout", "category": "food", "buildingIds": ["home", "food_court"]},
  {"id": "eat_at_a_restaurant", "label": "Eat at a Restaurant", "category": "food", "buildingIds": ["restaurant"]},
  {"id": "drink_coffee_or_tea", "label": "Drink Coffee or Tea", "category": "food", "buildingIds": ["cafe"]},
  {"id": "eat_dessert", "label": "Eat Dessert", "category": "food", "buildingIds": ["dessert_cafe"]},
  {"id": "have_a_barbecue", "label": "Have a Barbecue", "category": "food", "buildingIds": ["picnic_area"]},
  {"id": "enjoy_a_fancy_dinner", "label": "Enjoy a Fancy Dinner", "category": "food", "buildingIds": ["restaurant"]},
  {"id": "grab_a_snack", "label": "Grab a Snack", "category": "food", "buildingIds": ["home"]},
  {"id": "watch_tv", "label": "Watch TV", "category": "entertainment", "buildingIds": ["home"]},
  {"id": "watch_a_movie", "label": "Watch a Movie", "category": "entertainment", "buildingIds": ["movie_theater"]},
  {"id": "play_video_games", "label": "Play Video Games", "category": "entertainment", "buildingIds": ["video_game_lounge"]},
  {"id": "play_arcade_games", "label": "Play Arcade Games", "category": "entertainment", "buildingIds": ["arcade"]},
  {"id": "listen_to_music", "label": "Listen to Music", "category": "entertainment", "buildingIds": ["live_music_lounge"]},
  {"id": "dance", "label": "Dance", "category": "entertainment", "buildingIds": ["dance_hall", "dance_studio"]},
  {"id": "sing_karaoke", "label": "Sing Karaoke", "category": "entertainment", "buildingIds": ["karaoke_bar"]},
  {"id": "watch_comedy", "label": "Watch Comedy", "category": "entertainment", "buildingIds": ["comedy_club"]},
  {"id": "attend_a_concert", "label": "Attend a Concert", "category": "entertainment", "buildingIds": ["concert_hall"]},
  {"id": "play_board_games", "label": "Play Board Games", "category": "entertainment", "buildingIds": ["home"]},
  {"id": "take_a_nap", "label": "Take a Nap", "category": "wellness", "buildingIds": ["home"]},
  {"id": "sleep_in", "label": "Sleep In", "category": "wellness", "buildingIds": ["home"]},
  {"id": "take_a_bubble_bath", "label": "Take a Bubble Bath", "category": "wellness", "buildingIds": ["home"]},
  {"id": "get_a_massage", "label": "Get a Massage", "category": "wellness", "buildingIds": ["massage_spa"]},
  {"id": "visit_a_spa", "label": "Visit a Spa", "category": "wellness", "buildingIds": ["day_spa"]},
  {"id": "meditate", "label": "Meditate", "category": "wellness", "buildingIds": ["meditation_garden"]},
  {"id": "practice_yoga", "label": "Practice Yoga", "category": "wellness", "buildingIds": ["yoga_studio"]},
  {"id": "relax_in_a_hot_tub", "label": "Relax in a Hot Tub", "category": "wellness", "buildingIds": ["hot_springs"]},
  {"id": "lounge_by_the_pool", "label": "Lounge by the Pool", "category": "wellness", "buildingIds": ["public_swimming_pool"]},
  {"id": "enjoy_a_lazy_day", "label": "Enjoy a Lazy Day", "category": "wellness", "buildingIds": ["relaxation_lounge", "home"]},
  {"id": "walk_in_the_park", "label": "Walk in the Park", "category": "outdoors", "buildingIds": ["park"]},
  {"id": "have_a_picnic", "label": "Have a Picnic", "category": "outdoors", "buildingIds": ["picnic_area"]},
  {"id": "go_swimming", "label": "Go Swimming", "category": "outdoors", "buildingIds": ["indoor_swimming_pool", "public_swimming_pool"]},
  {"id": "ride_a_bicycle", "label": "Ride a Bicycle", "category": "outdoors", "buildingIds": ["park"]},
  {"id": "go_hiking", "label": "Go Hiking", "category": "outdoors", "buildingIds": ["hiking_trail"]},
  {"id": "go_fishing", "label": "Go Fishing", "category": "outdoors", "buildingIds": ["fishing_pier"]},
  {"id": "go_camping", "label": "Go Camping", "category": "outdoors", "buildingIds": ["campground"]},
  {"id": "visit_the_beach", "label": "Visit the Beach", "category": "outdoors", "buildingIds": ["beach"]},
  {"id": "stargaze", "label": "Stargaze", "category": "outdoors", "buildingIds": ["nature_preserve"]},
  {"id": "play_outdoor_games", "label": "Play Outdoor Games", "category": "outdoors", "buildingIds": ["park"]},
  {"id": "work_out_at_the_gym", "label": "Work Out at the Gym", "category": "fitness", "buildingIds": ["gym"]},
  {"id": "go_jogging", "label": "Go Jogging", "category": "fitness", "buildingIds": ["park"]},
  {"id": "play_basketball", "label": "Play Basketball", "category": "fitness", "buildingIds": ["basketball_court"]},
  {"id": "play_soccer", "label": "Play Soccer", "category": "fitness", "buildingIds": ["soccer_field"]},
  {"id": "play_tennis", "label": "Play Tennis", "category": "fitness", "buildingIds": ["tennis_courts"]},
  {"id": "go_bowling", "label": "Go Bowling", "category": "fitness", "buildingIds": ["bowling_alley"]},
  {"id": "go_skating", "label": "Go Skating", "category": "fitness", "buildingIds": ["skating_rink"]},
  {"id": "practice_martial_arts", "label": "Practice Martial Arts", "category": "fitness", "buildingIds": ["boxing_gym"]},
  {"id": "play_mini_golf", "label": "Play Mini Golf", "category": "fitness", "buildingIds": ["mini_golf_course"]},
  {"id": "compete_in_sports", "label": "Compete in Sports", "category": "fitness", "buildingIds": ["sports_complex"]},
  {"id": "learn_something_new", "label": "Learn Something New", "category": "growth", "buildingIds": ["school", "library"]},
  {"id": "read_a_book", "label": "Read a Book", "category": "growth", "buildingIds": ["library", "home"]},
  {"id": "complete_a_personal_goal", "label": "Complete a Personal Goal", "category": "growth", "buildingIds": ["home"]},
  {"id": "win_a_competition", "label": "Win a Competition", "category": "growth", "buildingIds": ["sports_complex"]},
  {"id": "improve_a_skill", "label": "Improve a Skill", "category": "growth", "buildingIds": ["hobby_workshop"]},
  {"id": "complete_a_challenge", "label": "Complete a Challenge", "category": "growth", "buildingIds": ["escape_room"]},
  {"id": "earn_an_award", "label": "Earn an Award", "category": "growth", "buildingIds": ["home"]},
  {"id": "break_a_personal_record", "label": "Break a Personal Record", "category": "growth", "buildingIds": ["sports_complex"]},
  {"id": "practice_a_talent", "label": "Practice a Talent", "category": "growth", "buildingIds": ["community_arts_center"]},
  {"id": "celebrate_an_achievement", "label": "Celebrate an Achievement", "category": "growth", "buildingIds": ["home", "restaurant"]},
  {"id": "play_with_a_cat", "label": "Play with a Cat", "category": "pets", "buildingIds": ["home"]},
  {"id": "walk_a_dog", "label": "Walk a Dog", "category": "pets", "buildingIds": ["dog_park", "park"]},
  {"id": "care_for_a_bunny", "label": "Care for a Bunny", "category": "pets", "buildingIds": ["home"]},
  {"id": "watch_aquarium_fish", "label": "Watch Aquarium Fish", "category": "pets", "buildingIds": ["home"]},
  {"id": "tend_a_garden", "label": "Tend a Garden", "category": "creative", "buildingIds": ["community_garden", "botanical_garden"]},
  {"id": "paint_a_picture", "label": "Paint a Picture", "category": "creative", "buildingIds": ["community_arts_center", "home"]},
  {"id": "take_photographs", "label": "Take Photographs", "category": "creative", "buildingIds": ["photography_studio", "park"]},
  {"id": "receive_praise", "label": "Receive Praise", "category": "social", "buildingIds": ["home"]},
];

export default ACTIVITIES;
