// Building templates only. category uses the four foundation types; subcategory is optional.
export const BUILDINGS = [
  {"id": "corporate_office", "label": "Corporate Office", "category": "work", "relatedProfessions": ["business_advisor", "business_management_assistant", "business_coach", "startup_advisor", "operations_assistant", "sales_assistant", "customer_service_agent", "business_strategy_consultant", "project_manager", "event_planning_assistant", "executive_assistant", "personal_assistant", "travel_planner", "office_administration_assistant"]},
  {"id": "bank", "label": "Bank", "category": "work", "relatedProfessions": ["financial_planning_assistant", "accounting_assistant", "bookkeeping_agent", "budget_planner", "investment_research_analyst", "tax_preparation_assistant", "financial_analyst", "loan_application_assistant"]},
  {"id": "law_firm", "label": "Law Firm", "category": "work", "relatedProfessions": ["legal_research_assistant", "legal_document_assistant", "contract_review_assistant", "legal_information_assistant", "tax_law_research_assistant", "business_law_research_assistant", "family_law_information_assistant"]},
  {"id": "health_center", "label": "Health Center", "category": "work", "relatedProfessions": ["medical_information_assistant", "nursing_education_assistant", "medication_information_assistant", "nutrition_planning_assistant", "fitness_coach", "mental_health_support_assistant", "wellness_coach", "medical_research_assistant"]},
  {"id": "research_lab", "label": "Research Lab", "category": "work", "relatedProfessions": ["science_research_assistant", "biology_research_assistant", "chemistry_research_assistant", "physics_research_assistant", "environmental_research_analyst", "research_assistant", "lab_data_analyst", "science_tutor", "data_analyst", "market_researcher", "business_analyst", "statistics_assistant", "research_analyst", "data_scientist", "researcher"]},
  {"id": "tech_center", "label": "Tech Center", "category": "work", "relatedProfessions": ["software_developer", "website_developer", "computer_programmer", "it_support_agent", "cybersecurity_assistant", "app_developer", "ai_developer", "technical_troubleshooting_assistant", "junior_developer"]},
  {"id": "publishing_house", "label": "Publishing House", "category": "work", "relatedProfessions": ["writer", "editor", "copywriter", "journalism_research_assistant", "speechwriter", "scriptwriter", "translator", "public_relations_assistant"]},
  {"id": "design_studio", "label": "Design Studio", "category": "work", "relatedProfessions": ["graphic_design_assistant", "digital_artist", "creative_director_assistant", "photo_editing_assistant", "video_editing_assistant", "animation_assistant", "interior_design_assistant", "fashion_design_assistant"]},
  {"id": "production_studio", "label": "Production Studio", "category": "work", "relatedProfessions": ["songwriter", "music_production_assistant", "music_creative_director", "podcast_producer", "film_production_assistant", "talent_management_assistant"]},
  {"id": "advertising_agency", "label": "Advertising Agency", "category": "work", "relatedProfessions": ["marketing_strategist", "social_media_manager", "content_creator", "brand_strategist", "advertising_specialist", "seo_specialist"]},
  {"id": "school", "label": "School", "category": "work", "relatedProfessions": ["ai_tutor", "lesson_planning_assistant", "academic_research_assistant", "career_guidance_assistant", "learning_coach", "training_instructor"]},
  {"id": "counseling_center", "label": "Counseling Center", "category": "work", "relatedProfessions": ["psychology_research_assistant", "relationship_coach", "relationship_communication_assistant", "life_coach", "communication_coach", "family_communication_assistant"]},
  {"id": "gym", "label": "Gym / Fitness Center", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "basketball_court", "label": "Basketball Court", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "football_field", "label": "Football Field", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "soccer_field", "label": "Soccer Field", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "baseball_stadium", "label": "Baseball Stadium", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "tennis_courts", "label": "Tennis Courts", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "bowling_alley", "label": "Bowling Alley", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "skating_rink", "label": "Skating Rink", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "boxing_gym", "label": "Boxing Gym", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "golf_course", "label": "Golf Course", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "sports_complex", "label": "Sports Complex", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "indoor_swimming_pool", "label": "Indoor Swimming Pool", "category": "recreational", "relatedProfessions": [], "subcategory": "sports"},
  {"id": "movie_theater", "label": "Movie Theater", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "comedy_club", "label": "Comedy Club", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "nightclub", "label": "Nightclub", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "karaoke_bar", "label": "Karaoke Bar", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "concert_hall", "label": "Concert Hall", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "performing_arts_theater", "label": "Performing Arts Theater", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "casino", "label": "Casino", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "arcade", "label": "Arcade", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "live_music_lounge", "label": "Live Music Lounge", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "dance_hall", "label": "Dance Hall", "category": "recreational", "relatedProfessions": [], "subcategory": "entertainment"},
  {"id": "park", "label": "Public Park", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "playground", "label": "Playground", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "botanical_garden", "label": "Botanical Garden", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "dog_park", "label": "Dog Park", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "skate_park", "label": "Skate Park", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "hiking_trail", "label": "Hiking Trail", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "campground", "label": "Campground", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "picnic_area", "label": "Picnic Area", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "nature_preserve", "label": "Nature Preserve", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "community_garden", "label": "Community Garden", "category": "recreational", "relatedProfessions": [], "subcategory": "outdoors"},
  {"id": "restaurant", "label": "Restaurant", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "cafe", "label": "Coffee Shop", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "sports_bar", "label": "Sports Bar", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "ice_cream_shop", "label": "Ice Cream Shop", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "food_court", "label": "Food Court", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "rooftop_lounge", "label": "Rooftop Lounge", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "juice_bar", "label": "Juice Bar", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "food_truck_park", "label": "Food Truck Park", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "dessert_cafe", "label": "Dessert Café", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "outdoor_beer_garden", "label": "Outdoor Beer Garden", "category": "recreational", "relatedProfessions": [], "subcategory": "food"},
  {"id": "beach", "label": "Beach", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "water_park", "label": "Water Park", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "marina", "label": "Marina", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "fishing_pier", "label": "Fishing Pier", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "public_swimming_pool", "label": "Public Swimming Pool", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "surfing_beach", "label": "Surfing Beach", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "boat_rental_dock", "label": "Boat Rental Dock", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "lakefront_park", "label": "Lakefront Park", "category": "recreational", "relatedProfessions": [], "subcategory": "water"},
  {"id": "video_game_lounge", "label": "Video Game Lounge", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "virtual_reality_arcade", "label": "Virtual Reality Arcade", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "escape_room", "label": "Escape Room", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "laser_tag_arena", "label": "Laser Tag Arena", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "paintball_field", "label": "Paintball Field", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "go_kart_track", "label": "Go-Kart Track", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "mini_golf_course", "label": "Mini Golf Course", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "indoor_trampoline_park", "label": "Indoor Trampoline Park", "category": "recreational", "relatedProfessions": [], "subcategory": "gaming"},
  {"id": "art_gallery", "label": "Art Gallery", "category": "recreational", "relatedProfessions": [], "subcategory": "culture"},
  {"id": "museum", "label": "Museum", "category": "recreational", "relatedProfessions": [], "subcategory": "culture"},
  {"id": "library", "label": "Library", "category": "recreational", "relatedProfessions": ["researcher"], "subcategory": "culture"},
  {"id": "pottery_studio", "label": "Pottery Studio", "category": "recreational", "relatedProfessions": [], "subcategory": "culture"},
  {"id": "dance_studio", "label": "Dance Studio", "category": "recreational", "relatedProfessions": [], "subcategory": "culture"},
  {"id": "photography_studio", "label": "Photography Studio", "category": "recreational", "relatedProfessions": [], "subcategory": "culture"},
  {"id": "community_arts_center", "label": "Community Arts Center", "category": "recreational", "relatedProfessions": [], "subcategory": "culture"},
  {"id": "hobby_workshop", "label": "Hobby Workshop", "category": "recreational", "relatedProfessions": [], "subcategory": "culture"},
  {"id": "day_spa", "label": "Day Spa", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "sauna_steam_room", "label": "Sauna & Steam Room", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "yoga_studio", "label": "Yoga Studio", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "meditation_garden", "label": "Meditation Garden", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "wellness_retreat", "label": "Wellness Retreat", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "massage_spa", "label": "Massage Spa", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "hot_springs", "label": "Hot Springs", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "relaxation_lounge", "label": "Relaxation Lounge", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "resort", "label": "Resort", "category": "recreational", "relatedProfessions": [], "subcategory": "wellness"},
  {"id": "home", "label": "Project Home", "category": "residential", "relatedProfessions": ["personal_assistant"]},
  {"id": "townhall", "label": "Town Hall", "category": "infrastructure", "relatedProfessions": ["mayor"]},
  {"id": "police_station", "label": "Police Station", "category": "infrastructure", "relatedProfessions": ["police_officer"]},
  {"id": "fire_station", "label": "Fire Station", "category": "infrastructure", "relatedProfessions": ["firefighter"]},
  {"id": "city_dump", "label": "City Dump", "category": "infrastructure", "relatedProfessions": ["sanitation_worker"]},
];

export default BUILDINGS;
