// Interest catalog (requested filename). happinessValue is a draft +5 matching-action value, not a live rule.
export const INTERESTS = [
  {"id": "favorite_meals", "label": "Favorite Meals", "category": "food", "happinessValue": 5, "relatedItems": ["favorite_meal"], "relatedPets": [], "relatedActivities": ["eat_a_favorite_meal"]},
  {"id": "ice_cream", "label": "Ice Cream", "category": "food", "happinessValue": 5, "relatedItems": ["ice_cream"], "relatedPets": [], "relatedActivities": ["eat_ice_cream"]},
  {"id": "sweets", "label": "Candy and Chocolate", "category": "food", "happinessValue": 5, "relatedItems": ["chocolate", "candy"], "relatedPets": [], "relatedActivities": ["enjoy_candy_or_chocolate"]},
  {"id": "takeout", "label": "Takeout", "category": "food", "happinessValue": 5, "relatedItems": ["takeout_meal"], "relatedPets": [], "relatedActivities": ["order_takeout"]},
  {"id": "dining_out", "label": "Dining Out", "category": "food", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["eat_at_a_restaurant"]},
  {"id": "coffee_and_tea", "label": "Coffee and Tea", "category": "food", "happinessValue": 5, "relatedItems": ["coffee", "tea"], "relatedPets": [], "relatedActivities": ["drink_coffee_or_tea"]},
  {"id": "desserts", "label": "Desserts", "category": "food", "happinessValue": 5, "relatedItems": ["dessert"], "relatedPets": [], "relatedActivities": ["eat_dessert"]},
  {"id": "barbecues", "label": "Barbecues", "category": "food", "happinessValue": 5, "relatedItems": ["barbecue_grill"], "relatedPets": [], "relatedActivities": ["have_a_barbecue"]},
  {"id": "fine_dining", "label": "Fine Dining", "category": "food", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["enjoy_a_fancy_dinner"]},
  {"id": "snacks", "label": "Snacks", "category": "food", "happinessValue": 5, "relatedItems": ["snack_fridge"], "relatedPets": [], "relatedActivities": ["grab_a_snack"]},
  {"id": "television", "label": "Television", "category": "entertainment", "happinessValue": 5, "relatedItems": ["television"], "relatedPets": [], "relatedActivities": ["watch_tv"]},
  {"id": "movies", "label": "Movies", "category": "entertainment", "happinessValue": 5, "relatedItems": ["television"], "relatedPets": [], "relatedActivities": ["watch_a_movie"]},
  {"id": "video_games", "label": "Video Games", "category": "entertainment", "happinessValue": 5, "relatedItems": ["game_console"], "relatedPets": [], "relatedActivities": ["play_video_games"]},
  {"id": "arcade_games", "label": "Arcade Games", "category": "entertainment", "happinessValue": 5, "relatedItems": ["arcade"], "relatedPets": [], "relatedActivities": ["play_arcade_games"]},
  {"id": "music", "label": "Music", "category": "entertainment", "happinessValue": 5, "relatedItems": ["record_player"], "relatedPets": [], "relatedActivities": ["listen_to_music"]},
  {"id": "dancing", "label": "Dancing", "category": "entertainment", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["dance"]},
  {"id": "karaoke", "label": "Karaoke", "category": "entertainment", "happinessValue": 5, "relatedItems": ["microphone"], "relatedPets": [], "relatedActivities": ["sing_karaoke"]},
  {"id": "comedy", "label": "Comedy", "category": "entertainment", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["watch_comedy"]},
  {"id": "concerts", "label": "Concerts", "category": "entertainment", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["attend_a_concert"]},
  {"id": "board_games", "label": "Board Games", "category": "entertainment", "happinessValue": 5, "relatedItems": ["board_game"], "relatedPets": [], "relatedActivities": ["play_board_games"]},
  {"id": "naps", "label": "Naps", "category": "wellness", "happinessValue": 5, "relatedItems": ["bed"], "relatedPets": [], "relatedActivities": ["take_a_nap"]},
  {"id": "sleeping_in", "label": "Sleeping In", "category": "wellness", "happinessValue": 5, "relatedItems": ["bed"], "relatedPets": [], "relatedActivities": ["sleep_in"]},
  {"id": "bubble_baths", "label": "Bubble Baths", "category": "wellness", "happinessValue": 5, "relatedItems": ["bathtub"], "relatedPets": [], "relatedActivities": ["take_a_bubble_bath"]},
  {"id": "massages", "label": "Massages", "category": "wellness", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["get_a_massage"]},
  {"id": "spa_visits", "label": "Spa Visits", "category": "wellness", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["visit_a_spa"]},
  {"id": "meditation", "label": "Meditation", "category": "wellness", "happinessValue": 5, "relatedItems": ["meditation_cushion"], "relatedPets": [], "relatedActivities": ["meditate"]},
  {"id": "yoga", "label": "Yoga", "category": "wellness", "happinessValue": 5, "relatedItems": ["yoga_mat"], "relatedPets": [], "relatedActivities": ["practice_yoga"]},
  {"id": "hot_tubs", "label": "Hot Tubs", "category": "wellness", "happinessValue": 5, "relatedItems": ["hot_tub"], "relatedPets": [], "relatedActivities": ["relax_in_a_hot_tub"]},
  {"id": "poolside_relaxation", "label": "Poolside Relaxation", "category": "wellness", "happinessValue": 5, "relatedItems": ["lounge_chair"], "relatedPets": [], "relatedActivities": ["lounge_by_the_pool"]},
  {"id": "lazy_days", "label": "Lazy Days", "category": "wellness", "happinessValue": 5, "relatedItems": ["armchair"], "relatedPets": [], "relatedActivities": ["enjoy_a_lazy_day"]},
  {"id": "park_walks", "label": "Park Walks", "category": "outdoors", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["walk_in_the_park"]},
  {"id": "picnics", "label": "Picnics", "category": "outdoors", "happinessValue": 5, "relatedItems": ["picnic_table", "picnic_basket"], "relatedPets": [], "relatedActivities": ["have_a_picnic"]},
  {"id": "swimming", "label": "Swimming", "category": "outdoors", "happinessValue": 5, "relatedItems": ["swimwear"], "relatedPets": [], "relatedActivities": ["go_swimming"]},
  {"id": "cycling", "label": "Cycling", "category": "outdoors", "happinessValue": 5, "relatedItems": ["bicycle"], "relatedPets": [], "relatedActivities": ["ride_a_bicycle"]},
  {"id": "hiking", "label": "Hiking", "category": "outdoors", "happinessValue": 5, "relatedItems": ["hiking_boots"], "relatedPets": [], "relatedActivities": ["go_hiking"]},
  {"id": "fishing", "label": "Fishing", "category": "outdoors", "happinessValue": 5, "relatedItems": ["fishing_rod"], "relatedPets": [], "relatedActivities": ["go_fishing"]},
  {"id": "camping", "label": "Camping", "category": "outdoors", "happinessValue": 5, "relatedItems": ["tent"], "relatedPets": [], "relatedActivities": ["go_camping"]},
  {"id": "beach_visits", "label": "Beach Visits", "category": "outdoors", "happinessValue": 5, "relatedItems": ["beach_towel"], "relatedPets": [], "relatedActivities": ["visit_the_beach"]},
  {"id": "stargazing", "label": "Stargazing", "category": "outdoors", "happinessValue": 5, "relatedItems": ["telescope"], "relatedPets": [], "relatedActivities": ["stargaze"]},
  {"id": "outdoor_games", "label": "Outdoor Games", "category": "outdoors", "happinessValue": 5, "relatedItems": ["outdoor_game_set"], "relatedPets": [], "relatedActivities": ["play_outdoor_games"]},
  {"id": "gym_workouts", "label": "Gym Workouts", "category": "fitness", "happinessValue": 5, "relatedItems": ["dumbbells"], "relatedPets": [], "relatedActivities": ["work_out_at_the_gym"]},
  {"id": "jogging", "label": "Jogging", "category": "fitness", "happinessValue": 5, "relatedItems": ["running_shoes"], "relatedPets": [], "relatedActivities": ["go_jogging"]},
  {"id": "basketball", "label": "Basketball", "category": "fitness", "happinessValue": 5, "relatedItems": ["basketball"], "relatedPets": [], "relatedActivities": ["play_basketball"]},
  {"id": "soccer", "label": "Soccer", "category": "fitness", "happinessValue": 5, "relatedItems": ["soccer_ball"], "relatedPets": [], "relatedActivities": ["play_soccer"]},
  {"id": "tennis", "label": "Tennis", "category": "fitness", "happinessValue": 5, "relatedItems": ["tennis_racket"], "relatedPets": [], "relatedActivities": ["play_tennis"]},
  {"id": "bowling", "label": "Bowling", "category": "fitness", "happinessValue": 5, "relatedItems": ["bowling_ball"], "relatedPets": [], "relatedActivities": ["go_bowling"]},
  {"id": "skating", "label": "Skating", "category": "fitness", "happinessValue": 5, "relatedItems": ["skates"], "relatedPets": [], "relatedActivities": ["go_skating"]},
  {"id": "martial_arts", "label": "Martial Arts", "category": "fitness", "happinessValue": 5, "relatedItems": ["training_mat"], "relatedPets": [], "relatedActivities": ["practice_martial_arts"]},
  {"id": "mini_golf", "label": "Mini Golf", "category": "fitness", "happinessValue": 5, "relatedItems": ["golf_club"], "relatedPets": [], "relatedActivities": ["play_mini_golf"]},
  {"id": "competitive_sports", "label": "Competitive Sports", "category": "fitness", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["compete_in_sports"]},
  {"id": "learning", "label": "Learning", "category": "growth", "happinessValue": 5, "relatedItems": ["book"], "relatedPets": [], "relatedActivities": ["learn_something_new"]},
  {"id": "reading", "label": "Reading", "category": "growth", "happinessValue": 5, "relatedItems": ["book", "low_shelf"], "relatedPets": [], "relatedActivities": ["read_a_book"]},
  {"id": "personal_goals", "label": "Personal Goals", "category": "growth", "happinessValue": 5, "relatedItems": ["goal_journal"], "relatedPets": [], "relatedActivities": ["complete_a_personal_goal"]},
  {"id": "competitions", "label": "Competitions", "category": "growth", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["win_a_competition"]},
  {"id": "skill_practice", "label": "Skill Practice", "category": "growth", "happinessValue": 5, "relatedItems": ["practice_notebook"], "relatedPets": [], "relatedActivities": ["improve_a_skill"]},
  {"id": "challenges", "label": "Challenges", "category": "growth", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["complete_a_challenge"]},
  {"id": "awards", "label": "Awards", "category": "growth", "happinessValue": 5, "relatedItems": ["award_trophy"], "relatedPets": [], "relatedActivities": ["earn_an_award"]},
  {"id": "personal_records", "label": "Personal Records", "category": "growth", "happinessValue": 5, "relatedItems": ["record_journal"], "relatedPets": [], "relatedActivities": ["break_a_personal_record"]},
  {"id": "talent_practice", "label": "Talent Practice", "category": "growth", "happinessValue": 5, "relatedItems": ["guitar"], "relatedPets": [], "relatedActivities": ["practice_a_talent"]},
  {"id": "celebrations", "label": "Celebrations", "category": "growth", "happinessValue": 5, "relatedItems": ["celebration_cake"], "relatedPets": [], "relatedActivities": ["celebrate_an_achievement"]},
  {"id": "cat_companionship", "label": "Cat Companionship", "category": "pets", "happinessValue": 5, "relatedItems": ["pet_toy"], "relatedPets": ["cat"], "relatedActivities": ["play_with_a_cat"]},
  {"id": "dog_companionship", "label": "Dog Companionship", "category": "pets", "happinessValue": 5, "relatedItems": ["pet_toy"], "relatedPets": ["dog"], "relatedActivities": ["walk_a_dog"]},
  {"id": "bunny_companionship", "label": "Bunny Companionship", "category": "pets", "happinessValue": 5, "relatedItems": ["pet_toy"], "relatedPets": ["bunny"], "relatedActivities": ["care_for_a_bunny"]},
  {"id": "aquatic_pets", "label": "Aquatic Pets", "category": "pets", "happinessValue": 5, "relatedItems": ["aquarium"], "relatedPets": ["fish"], "relatedActivities": ["watch_aquarium_fish"]},
  {"id": "gardening", "label": "Gardening", "category": "creative", "happinessValue": 5, "relatedItems": ["garden_bed", "flower_patch"], "relatedPets": [], "relatedActivities": ["tend_a_garden"]},
  {"id": "painting", "label": "Painting", "category": "creative", "happinessValue": 5, "relatedItems": ["easel"], "relatedPets": [], "relatedActivities": ["paint_a_picture"]},
  {"id": "photography", "label": "Photography", "category": "creative", "happinessValue": 5, "relatedItems": ["camera"], "relatedPets": [], "relatedActivities": ["take_photographs"]},
  {"id": "praise", "label": "Encouragement", "category": "social", "happinessValue": 5, "relatedItems": [], "relatedPets": [], "relatedActivities": ["receive_praise"]},
];

export default INTERESTS;
