// Interest item definitions. decorId links existing decor; null means future content.
export const ITEMS = [
  {"id": "aquarium", "label": "Aquarium", "category": "decor", "decorId": "aquarium"},
  {"id": "arcade", "label": "Arcade", "category": "decor", "decorId": "arcade"},
  {"id": "armchair", "label": "Armchair", "category": "decor", "decorId": "armchair"},
  {"id": "award_trophy", "label": "Award Trophy", "category": "equipment", "decorId": null},
  {"id": "barbecue_grill", "label": "Barbecue Grill", "category": "equipment", "decorId": null},
  {"id": "basketball", "label": "Basketball", "category": "equipment", "decorId": null},
  {"id": "bathtub", "label": "Bathtub", "category": "equipment", "decorId": null},
  {"id": "beach_towel", "label": "Beach Towel", "category": "equipment", "decorId": null},
  {"id": "bed", "label": "Bed", "category": "equipment", "decorId": null},
  {"id": "bicycle", "label": "Bicycle", "category": "equipment", "decorId": null},
  {"id": "board_game", "label": "Board Game", "category": "equipment", "decorId": null},
  {"id": "book", "label": "Book", "category": "equipment", "decorId": null},
  {"id": "bowling_ball", "label": "Bowling Ball", "category": "equipment", "decorId": null},
  {"id": "camera", "label": "Camera", "category": "equipment", "decorId": null},
  {"id": "candy", "label": "Candy", "category": "treat", "decorId": null},
  {"id": "celebration_cake", "label": "Celebration Cake", "category": "treat", "decorId": null},
  {"id": "chocolate", "label": "Chocolate", "category": "treat", "decorId": null},
  {"id": "coffee", "label": "Coffee", "category": "treat", "decorId": null},
  {"id": "dessert", "label": "Dessert", "category": "treat", "decorId": null},
  {"id": "dumbbells", "label": "Dumbbells", "category": "equipment", "decorId": null},
  {"id": "easel", "label": "Easel", "category": "equipment", "decorId": null},
  {"id": "favorite_meal", "label": "Favorite Meal", "category": "treat", "decorId": null},
  {"id": "fishing_rod", "label": "Fishing Rod", "category": "equipment", "decorId": null},
  {"id": "flower_patch", "label": "Flower Patch", "category": "decor", "decorId": "flower_patch"},
  {"id": "game_console", "label": "Game Console", "category": "equipment", "decorId": null},
  {"id": "garden_bed", "label": "Garden Bed", "category": "decor", "decorId": "garden_bed"},
  {"id": "goal_journal", "label": "Goal Journal", "category": "equipment", "decorId": null},
  {"id": "golf_club", "label": "Golf Club", "category": "equipment", "decorId": null},
  {"id": "guitar", "label": "Guitar", "category": "decor", "decorId": "guitar"},
  {"id": "hiking_boots", "label": "Hiking Boots", "category": "equipment", "decorId": null},
  {"id": "hot_tub", "label": "Hot Tub", "category": "equipment", "decorId": null},
  {"id": "ice_cream", "label": "Ice Cream", "category": "treat", "decorId": null},
  {"id": "lounge_chair", "label": "Lounge Chair", "category": "equipment", "decorId": null},
  {"id": "low_shelf", "label": "Low Shelf", "category": "decor", "decorId": "low_shelf"},
  {"id": "meditation_cushion", "label": "Meditation Cushion", "category": "equipment", "decorId": null},
  {"id": "microphone", "label": "Microphone", "category": "equipment", "decorId": null},
  {"id": "outdoor_game_set", "label": "Outdoor Game Set", "category": "equipment", "decorId": null},
  {"id": "pet_toy", "label": "Pet Toy", "category": "equipment", "decorId": null},
  {"id": "picnic_basket", "label": "Picnic Basket", "category": "equipment", "decorId": null},
  {"id": "picnic_table", "label": "Picnic Table", "category": "decor", "decorId": "picnic_table"},
  {"id": "practice_notebook", "label": "Practice Notebook", "category": "equipment", "decorId": null},
  {"id": "record_journal", "label": "Record Journal", "category": "equipment", "decorId": null},
  {"id": "record_player", "label": "Record Player", "category": "decor", "decorId": "record_player"},
  {"id": "running_shoes", "label": "Running Shoes", "category": "equipment", "decorId": null},
  {"id": "skates", "label": "Skates", "category": "equipment", "decorId": null},
  {"id": "snack_fridge", "label": "Snack Fridge", "category": "decor", "decorId": "snack_fridge"},
  {"id": "soccer_ball", "label": "Soccer Ball", "category": "equipment", "decorId": null},
  {"id": "swimwear", "label": "Swimwear", "category": "equipment", "decorId": null},
  {"id": "takeout_meal", "label": "Takeout Meal", "category": "treat", "decorId": null},
  {"id": "tea", "label": "Tea", "category": "treat", "decorId": null},
  {"id": "telescope", "label": "Telescope", "category": "equipment", "decorId": null},
  {"id": "television", "label": "Television", "category": "equipment", "decorId": null},
  {"id": "tennis_racket", "label": "Tennis Racket", "category": "equipment", "decorId": null},
  {"id": "tent", "label": "Tent", "category": "equipment", "decorId": null},
  {"id": "training_mat", "label": "Training Mat", "category": "equipment", "decorId": null},
  {"id": "yoga_mat", "label": "Yoga Mat", "category": "equipment", "decorId": null},
];

export default ITEMS;
