// Profession catalog. buildingAffinity contains building catalog IDs, not placed instance IDs.
export const PROFESSIONS = [
  {"id": "business_advisor", "label": "Business Advisor", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "business_management_assistant", "label": "Business Management Assistant", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "business_coach", "label": "Business Coach", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "startup_advisor", "label": "Startup Advisor", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "operations_assistant", "label": "Operations Assistant", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "sales_assistant", "label": "Sales Assistant", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "customer_service_agent", "label": "Customer Service Agent", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "business_strategy_consultant", "label": "Business Strategy Consultant", "category": "business", "buildingAffinity": ["corporate_office"]},
  {"id": "financial_planning_assistant", "label": "Financial Planning Assistant", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "accounting_assistant", "label": "Accounting Assistant", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "bookkeeping_agent", "label": "Bookkeeping Agent", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "budget_planner", "label": "Budget Planner", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "investment_research_analyst", "label": "Investment Research Analyst", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "tax_preparation_assistant", "label": "Tax Preparation Assistant", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "financial_analyst", "label": "Financial Analyst", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "loan_application_assistant", "label": "Loan Application Assistant", "category": "finance", "buildingAffinity": ["bank"]},
  {"id": "legal_research_assistant", "label": "Legal Research Assistant", "category": "legal", "buildingAffinity": ["law_firm"]},
  {"id": "legal_document_assistant", "label": "Legal Document Assistant", "category": "legal", "buildingAffinity": ["law_firm"]},
  {"id": "contract_review_assistant", "label": "Contract Review Assistant", "category": "legal", "buildingAffinity": ["law_firm"]},
  {"id": "legal_information_assistant", "label": "Legal Information Assistant", "category": "legal", "buildingAffinity": ["law_firm"]},
  {"id": "tax_law_research_assistant", "label": "Tax Law Research Assistant", "category": "legal", "buildingAffinity": ["law_firm"]},
  {"id": "business_law_research_assistant", "label": "Business Law Research Assistant", "category": "legal", "buildingAffinity": ["law_firm"]},
  {"id": "family_law_information_assistant", "label": "Family Law Information Assistant", "category": "legal", "buildingAffinity": ["law_firm"]},
  {"id": "medical_information_assistant", "label": "Medical Information Assistant", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "nursing_education_assistant", "label": "Nursing Education Assistant", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "medication_information_assistant", "label": "Medication Information Assistant", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "nutrition_planning_assistant", "label": "Nutrition Planning Assistant", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "fitness_coach", "label": "Fitness Coach", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "mental_health_support_assistant", "label": "Mental Health Support Assistant", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "wellness_coach", "label": "Wellness Coach", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "medical_research_assistant", "label": "Medical Research Assistant", "category": "health", "buildingAffinity": ["health_center"]},
  {"id": "science_research_assistant", "label": "Science Research Assistant", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "biology_research_assistant", "label": "Biology Research Assistant", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "chemistry_research_assistant", "label": "Chemistry Research Assistant", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "physics_research_assistant", "label": "Physics Research Assistant", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "environmental_research_analyst", "label": "Environmental Research Analyst", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "research_assistant", "label": "Research Assistant", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "lab_data_analyst", "label": "Lab Data Analyst", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "science_tutor", "label": "Science Tutor", "category": "science", "buildingAffinity": ["research_lab"]},
  {"id": "software_developer", "label": "Software Developer", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "website_developer", "label": "Website Developer", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "computer_programmer", "label": "Computer Programmer", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "it_support_agent", "label": "IT Support Agent", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "cybersecurity_assistant", "label": "Cybersecurity Assistant", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "app_developer", "label": "App Developer", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "ai_developer", "label": "AI Developer", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "technical_troubleshooting_assistant", "label": "Technical Troubleshooting Assistant", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "writer", "label": "Writer", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "editor", "label": "Editor", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "copywriter", "label": "Copywriter", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "journalism_research_assistant", "label": "Journalism Research Assistant", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "speechwriter", "label": "Speechwriter", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "scriptwriter", "label": "Scriptwriter", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "translator", "label": "Translator", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "public_relations_assistant", "label": "Public Relations Assistant", "category": "writing", "buildingAffinity": ["publishing_house"]},
  {"id": "graphic_design_assistant", "label": "Graphic Design Assistant", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "digital_artist", "label": "Digital Artist", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "creative_director_assistant", "label": "Creative Director Assistant", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "photo_editing_assistant", "label": "Photo Editing Assistant", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "video_editing_assistant", "label": "Video Editing Assistant", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "animation_assistant", "label": "Animation Assistant", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "interior_design_assistant", "label": "Interior Design Assistant", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "fashion_design_assistant", "label": "Fashion Design Assistant", "category": "design", "buildingAffinity": ["design_studio"]},
  {"id": "songwriter", "label": "Songwriter", "category": "entertainment", "buildingAffinity": ["production_studio"]},
  {"id": "music_production_assistant", "label": "Music Production Assistant", "category": "entertainment", "buildingAffinity": ["production_studio"]},
  {"id": "music_creative_director", "label": "Music Creative Director", "category": "entertainment", "buildingAffinity": ["production_studio"]},
  {"id": "podcast_producer", "label": "Podcast Producer", "category": "entertainment", "buildingAffinity": ["production_studio"]},
  {"id": "film_production_assistant", "label": "Film Production Assistant", "category": "entertainment", "buildingAffinity": ["production_studio"]},
  {"id": "talent_management_assistant", "label": "Talent Management Assistant", "category": "entertainment", "buildingAffinity": ["production_studio"]},
  {"id": "marketing_strategist", "label": "Marketing Strategist", "category": "marketing", "buildingAffinity": ["advertising_agency"]},
  {"id": "social_media_manager", "label": "Social Media Manager", "category": "marketing", "buildingAffinity": ["advertising_agency"]},
  {"id": "content_creator", "label": "Content Creator", "category": "marketing", "buildingAffinity": ["advertising_agency"]},
  {"id": "brand_strategist", "label": "Brand Strategist", "category": "marketing", "buildingAffinity": ["advertising_agency"]},
  {"id": "advertising_specialist", "label": "Advertising Specialist", "category": "marketing", "buildingAffinity": ["advertising_agency"]},
  {"id": "seo_specialist", "label": "SEO Specialist", "category": "marketing", "buildingAffinity": ["advertising_agency"]},
  {"id": "ai_tutor", "label": "AI Tutor", "category": "education", "buildingAffinity": ["school"]},
  {"id": "lesson_planning_assistant", "label": "Lesson Planning Assistant", "category": "education", "buildingAffinity": ["school"]},
  {"id": "academic_research_assistant", "label": "Academic Research Assistant", "category": "education", "buildingAffinity": ["school"]},
  {"id": "career_guidance_assistant", "label": "Career Guidance Assistant", "category": "education", "buildingAffinity": ["school"]},
  {"id": "learning_coach", "label": "Learning Coach", "category": "education", "buildingAffinity": ["school"]},
  {"id": "training_instructor", "label": "Training Instructor", "category": "education", "buildingAffinity": ["school"]},
  {"id": "psychology_research_assistant", "label": "Psychology Research Assistant", "category": "relationships", "buildingAffinity": ["counseling_center"]},
  {"id": "relationship_coach", "label": "Relationship Coach", "category": "relationships", "buildingAffinity": ["counseling_center"]},
  {"id": "relationship_communication_assistant", "label": "Relationship Communication Assistant", "category": "relationships", "buildingAffinity": ["counseling_center"]},
  {"id": "life_coach", "label": "Life Coach", "category": "relationships", "buildingAffinity": ["counseling_center"]},
  {"id": "communication_coach", "label": "Communication Coach", "category": "relationships", "buildingAffinity": ["counseling_center"]},
  {"id": "family_communication_assistant", "label": "Family Communication Assistant", "category": "relationships", "buildingAffinity": ["counseling_center"]},
  {"id": "project_manager", "label": "Project Manager", "category": "organization", "buildingAffinity": ["corporate_office"]},
  {"id": "event_planning_assistant", "label": "Event Planning Assistant", "category": "organization", "buildingAffinity": ["corporate_office"]},
  {"id": "executive_assistant", "label": "Executive Assistant", "category": "organization", "buildingAffinity": ["corporate_office"]},
  {"id": "personal_assistant", "label": "Personal Assistant", "category": "organization", "buildingAffinity": ["home", "corporate_office"]},
  {"id": "travel_planner", "label": "Travel Planner", "category": "organization", "buildingAffinity": ["corporate_office"]},
  {"id": "office_administration_assistant", "label": "Office Administration Assistant", "category": "organization", "buildingAffinity": ["corporate_office"]},
  {"id": "data_analyst", "label": "Data Analyst", "category": "data", "buildingAffinity": ["research_lab"]},
  {"id": "market_researcher", "label": "Market Researcher", "category": "data", "buildingAffinity": ["research_lab"]},
  {"id": "business_analyst", "label": "Business Analyst", "category": "data", "buildingAffinity": ["research_lab"]},
  {"id": "statistics_assistant", "label": "Statistics Assistant", "category": "data", "buildingAffinity": ["research_lab"]},
  {"id": "research_analyst", "label": "Research Analyst", "category": "data", "buildingAffinity": ["research_lab"]},
  {"id": "data_scientist", "label": "Data Scientist", "category": "data", "buildingAffinity": ["research_lab"]},
  {"id": "junior_developer", "label": "Junior Developer", "category": "technology", "buildingAffinity": ["tech_center"]},
  {"id": "researcher", "label": "Researcher", "category": "science", "buildingAffinity": ["research_lab", "library"]},
  {"id": "mayor", "label": "Mayor", "category": "civic", "buildingAffinity": ["townhall"]},
  {"id": "police_officer", "label": "Police Officer", "category": "civic", "buildingAffinity": ["police_station"]},
  {"id": "firefighter", "label": "Firefighter", "category": "civic", "buildingAffinity": ["fire_station"]},
  {"id": "sanitation_worker", "label": "Sanitation Worker", "category": "civic", "buildingAffinity": ["city_dump"]},
];

export default PROFESSIONS;
