import {escapeHtml as esc} from './sim.js';
import {icon} from './icons.js';
export class ProjectsPanel{
 constructor(host,{focus,onCount}){this.host=host;this.focus=focus;this.onCount=onCount;this.homes=[];this.available=[];this.importing=false;this.parent='';this.message='';this.busy=false;this.form=false;this.requestKey=null;this.draft={name:'',folder:'',createFolder:true};
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||this.busy)return;if(b.hasAttribute('data-add-project')){this.form=true;this.importing=false;this.requestKey=crypto.randomUUID();this.render();host.querySelector('[name=name]')?.focus();}else if(b.hasAttribute('data-import-projects')){this.importing=true;this.form=false;this.load();}else if(b.dataset.removeProject)this.removeProject(b.dataset.removeProject);else if(b.dataset.importId)this.importProject(b.dataset.importId);else if(b.hasAttribute('data-cancel-project')){this.form=false;this.importing=false;this.render();}else if(b.hasAttribute('data-refresh-projects'))this.load();else if(b.dataset.projectFolder)this.focus(b.dataset.projectFolder);});
 host.addEventListener('input',e=>{if(['name','folder','createFolder'].includes(e.target.name))this.requestKey=crypto.randomUUID();if(e.target.name==='name'){const old=this.parent+'/'+this.slug(this.draft.name);this.draft.name=e.target.value;if(!this.draft.folder||this.draft.folder===old){this.draft.folder=this.parent+'/'+this.slug(this.draft.name);const field=host.querySelector('[name=folder]');if(field)field.value=this.draft.folder;}}else if(e.target.name==='folder')this.draft.folder=e.target.value;else if(e.target.name==='createFolder')this.draft.createFolder=e.target.checked;});
 host.addEventListener('submit',e=>{e.preventDefault();if(!this.busy)this.create();});
 }
 slug(name){return name.trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-|-$/g,'')||'new-project';}
 setHomes(homes){this.homes=homes.filter(h=>h.project.startsWith('/'));if(!this.form)this.render();}
 async post(input){const r=await fetch('/api/codex-projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const body=await r.json();if(!r.ok)throw Error(body.error||'Project request failed.');return body.result;}
 async load(){if(this.busy)return;this.busy=true;this.message='Loading local Codex projects…';this.render();try{const r=await this.post({action:'list'});this.parent=r.defaultParent;this.available=r.projects;this.message=r.skipped?`${r.skipped} projects have unavailable local folders.`:'';this.setHomes(r.homes);}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 async importProject(id){this.busy=true;this.message='Importing project…';this.render();try{const r=await this.post({action:'import',id});this.homes=this.homes.filter(h=>h.project!==r.home.project).concat(r.home);this.message='Project imported. Its home is ready.';this.importing=false;setTimeout(()=>this.focus(r.home.project),500);}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 async removeProject(project){this.busy=true;this.message='Removing project from your world…';this.render();try{await this.post({action:'remove',project});this.homes=this.homes.filter(h=>h.project!==project);this.message='Project and home removed. Files and chats are preserved.';}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 async create(){this.busy=true;this.message='Creating the Codex project and home…';this.render();try{const r=await this.post({action:'create',...this.draft,idempotencyKey:this.requestKey});this.form=false;this.draft={name:'',folder:'',createFolder:true};this.message=r.project.existing?'Connected the existing Codex project.':'Project and home created.';this.homes=this.homes.filter(h=>h.project!==r.home.project).concat(r.home);this.focus(r.home.project);setTimeout(()=>this.focus(r.home.project),500);}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 render(){const homes=[...this.homes].sort((a,b)=>(a.name||a.project).localeCompare(b.name||b.project));this.onCount(homes.length);
 const busy=this.busy?'disabled':'';const added=p=>this.homes.some(h=>h.project===p.path);
 const actions=`<div class="project-list-actions"><span class="project-count">${homes.length} home${homes.length===1?'':'s'}</span><button type="button" class="pa-new" data-add-project ${busy}>${icon('folderPlus')} New</button><button type="button" class="pa-import" data-import-projects ${busy}>${icon('folderInput')} Import</button><button type="button" class="icon-btn pa-refresh" data-refresh-projects aria-label="Refresh Codex projects" title="Refresh" ${busy}>${icon('rotateCcw')}</button></div>`;
 const importList=this.importing?`<div class="project-import-list"><div class="project-sub-head"><b>Import a Codex project</b><button type="button" class="icon-btn" data-cancel-project aria-label="Close import">${icon('x')}</button></div>${this.available.map(p=>`<button type="button" class="local-project-row import-row" data-import-id="${esc(p.id)}" ${this.busy||added(p)?'disabled':''}><span class="project-tile">${icon('folderInput')}</span><span><b>${esc(p.name)}</b><small>${esc(p.path)}</small></span><em>${added(p)?'Added':'Add'}</em></button>`).join('')||'<p class="project-empty-note">No other Codex projects found.</p>'}</div>`:'';
 const form=this.form?`<form class="local-project-form"><div class="project-sub-head"><b>New project</b><button type="button" class="icon-btn" data-cancel-project aria-label="Cancel new project">${icon('x')}</button></div><label>Name<input name="name" maxlength="100" required placeholder="My project" value="${esc(this.draft.name)}" ${busy}></label><label>Folder<input name="folder" required placeholder="${esc(this.parent)}/my-project" value="${esc(this.draft.folder)}" ${busy}></label><label class="project-folder-choice"><input type="checkbox" name="createFolder" ${this.draft.createFolder?'checked':''} ${busy}> Create the folder if it's missing</label><div class="project-form-actions"><button type="submit" class="pa-new" ${busy}>${this.busy?'Creating…':'Add project'}</button><button type="button" class="pa-ghost" data-cancel-project ${busy}>Cancel</button></div></form>`:'';
 this.host.innerHTML=`${actions}${importList}${form}${this.message?`<p role="status" class="project-status">${icon('info')}<span>${esc(this.message)}</span></p>`:'<p role="status" class="project-status" hidden></p>'}<div class="local-project-list">${homes.map(h=>`<div class="project-card"><button type="button" class="local-project-row" data-project-folder="${esc(h.project)}" title="${esc(h.project)}"><span class="project-tile">${icon('house')}</span><span><b>${esc(h.name||h.project.split('/').pop())}</b><small>${h.codexProjectId?'Codex project':'Observed folder'} · ${h.characters.length} resident${h.characters.length===1?'':'s'}</small><small class="project-path">${esc(h.project)}</small></span></button><button type="button" class="project-remove" data-remove-project="${esc(h.project)}" aria-label="Remove ${esc(h.name||'project')} from Agent World" title="Remove this home from Agent World. Files and chats are preserved." ${busy}>${icon('trash')}</button></div>`).join('')||'<div class="empty">Add your first project. Create a new one or import an existing Codex project.</div>'}</div><small class="project-local-note">Local to this computer</small>`;
 }
}
