import {escapeHtml as esc} from './sim.js';
import {icon} from './icons.js';
import { homeBuildState, homeCompletionCost, TOWN_HALL } from '../../shared/gameplay.mjs';
export class ProjectsPanel{
 constructor(host,{focus,onCount}){this.host=host;this.focus=focus;this.onCount=onCount;this.homes=[];this.available=[];this.importing=false;this.parent='';this.message='';this.busy=false;this.form=false;this.requestKey=null;this.draft={name:'',folder:'',createFolder:true};
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||this.busy)return;if(b.hasAttribute('data-add-project')){this.form=true;this.importing=false;this.requestKey=crypto.randomUUID();this.render();host.querySelector('[name=name]')?.focus();}else if(b.hasAttribute('data-import-projects')){this.importing=true;this.form=false;this.load();}else if(b.dataset.removeProject)this.removeProject(b.dataset.removeProject);else if(b.dataset.importId)this.importProject(b.dataset.importId);else if(b.hasAttribute('data-cancel-project')){this.form=false;this.importing=false;this.render();}else if(b.hasAttribute('data-refresh-projects'))this.load();else if(b.dataset.projectFolder)this.focus(b.dataset.projectFolder);});
 host.addEventListener('input',e=>{if(['name','folder','createFolder'].includes(e.target.name))this.requestKey=crypto.randomUUID();if(e.target.name==='name'){const old=this.parent+'/'+this.slug(this.draft.name);this.draft.name=e.target.value;if(!this.draft.folder||this.draft.folder===old){this.draft.folder=this.parent+'/'+this.slug(this.draft.name);const field=host.querySelector('[name=folder]');if(field)field.value=this.draft.folder;}}else if(e.target.name==='folder')this.draft.folder=e.target.value;else if(e.target.name==='createFolder')this.draft.createFolder=e.target.checked;});
 host.addEventListener('submit',e=>{e.preventDefault();if(!this.busy)this.create();});
 host.addEventListener('click', e => { const b = e.target.closest('[data-home-speed]'); if (b && !this.busy) this.finishHome(b.dataset.homeSpeed); });
 this.timer = setInterval(() => this.updateConstruction(), 1000);
 }
 setGameState(gameplay, balance){this.gameplay=gameplay;this.balance=balance;this.updateConstruction();}
 updateConstruction(){
  for(const el of this.host.querySelectorAll('[data-home-build]')){
   const project=el.dataset.homeBuild,state=homeBuildState(this.gameplay,project),cost=homeCompletionCost(this.gameplay,project);
   el.hidden=state.status!=='building';
   el.querySelector('[data-home-time]').textContent=`${Math.ceil(state.remainingMs/60000)} min remaining`;
   el.querySelector('progress').value=TOWN_HALL.durationMs-state.remainingMs;
   const button=el.querySelector('[data-home-speed]');button.disabled=this.busy||this.balance<cost;
   button.querySelector('[data-home-cost]').textContent=`${cost} gems total`;
  }
 }
 constructionMarkup(home){
  if(homeBuildState(this.gameplay,home.project).status!=='building')return '';
  return `<div class="home-build-controls" data-home-build="${esc(home.project)}"><span data-home-time></span><progress max="${TOWN_HALL.durationMs}" aria-label="Home construction progress"></progress><button type="button" data-home-speed="${esc(home.project)}">${icon('zap')} Speed up build <span data-home-cost></span>${icon('gem')}</button></div>`;
 }
 async finishHome(project){this.busy=true;this.message='Finishing home construction…';this.render();try{
  const r=await fetch('/api/gameplay',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'expedite-home',project})});const data=await r.json();if(!r.ok)throw Error(data.error||'Construction failed.');this.gameplay=data.gameplay;this.message='Your home is ready. Your Personal Assistant can move in.';
 }catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 slug(name){return name.trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-|-$/g,'')||'new-project';}
 setHomes(homes){this.homes=homes.filter(h=>/^(\/|[A-Za-z]:[\\/])/.test(h.project));if(!this.form)this.render();}
 setTownHallReady(ready){if(this.townHallReady===ready)return;this.townHallReady=ready;this.render();}
 async post(input){const r=await fetch('/api/codex-projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const body=await r.json();if(!r.ok)throw Error(body.error||'Project request failed.');return body.result;}
 async load(){if(this.busy)return;this.busy=true;this.message='Loading local Codex projects…';this.render();try{const r=await this.post({action:'list'});this.parent=r.defaultParent;this.available=r.projects;this.message=r.skipped?`${r.skipped} projects have unavailable local folders.`:'';this.setHomes(r.homes);}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 async importProject(id){this.busy=true;this.message='Building a home for your project…';this.render();try{const r=await this.post({action:'import',id});this.homes=this.homes.filter(h=>h.project!==r.home.project).concat(r.home);this.message='Home construction started. Your Personal Assistant moves in when it is ready.';this.importing=false;setTimeout(()=>this.focus(r.home.project),500);}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 async removeProject(project){this.busy=true;this.message='Removing project from your world…';this.render();try{await this.post({action:'remove',project});this.homes=this.homes.filter(h=>h.project!==project);this.message='Project and home removed. Files and chats are preserved.';}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 async create(){this.busy=true;this.message='Building your home and creating its project…';this.render();try{const r=await this.post({action:'create',...this.draft,idempotencyKey:this.requestKey});this.form=false;this.draft={name:'',folder:'',createFolder:true};this.message='Home construction started. Your Personal Assistant moves in when it is ready.';this.homes=this.homes.filter(h=>h.project!==r.home.project).concat(r.home);this.focus(r.home.project);setTimeout(()=>this.focus(r.home.project),500);}catch(e){this.message=e.message;}finally{this.busy=false;this.render();}}
 render(){const homes=[...this.homes].sort((a,b)=>(a.name||a.project).localeCompare(b.name||b.project));this.onCount(homes.length);
 const busy=this.busy?'disabled':'';const buildDisabled=this.busy||!this.townHallReady?'disabled':'';const added=p=>this.homes.some(h=>h.project===p.path);
 const actions=`<div class="project-list-actions"><span class="project-count">${homes.length} home${homes.length===1?'':'s'}</span><button type="button" class="pa-new" data-add-project ${buildDisabled}>${icon('house')} Build home</button><button type="button" class="pa-import" data-import-projects ${buildDisabled}>${icon('folderInput')} Existing project</button><button type="button" class="icon-btn pa-refresh" data-refresh-projects aria-label="Refresh Codex projects" title="Refresh" ${busy}>${icon('rotateCcw')}</button></div>`;
 const importList=this.importing?`<div class="project-import-list"><div class="project-sub-head"><b>Build a home for an existing project</b><button type="button" class="icon-btn" data-cancel-project aria-label="Close import">${icon('x')}</button></div>${this.available.map(p=>`<button type="button" class="local-project-row import-row" data-import-id="${esc(p.id)}" ${this.busy||!this.townHallReady||added(p)?'disabled':''}><span class="project-tile">${icon('folderInput')}</span><span><b>${esc(p.name)}</b><small>${esc(p.path)}</small></span><em>${added(p)?'Built':'Build'}</em></button>`).join('')||'<p class="project-empty-note">No other Codex projects found.</p>'}</div>`:'';
 const form=this.form?`<form class="local-project-form"><div class="project-sub-head"><b>Build a new home</b><button type="button" class="icon-btn" data-cancel-project aria-label="Cancel new home">${icon('x')}</button></div><label>Home name<input name="name" maxlength="100" required placeholder="My home" value="${esc(this.draft.name)}" ${busy}></label><label>Project folder<input name="folder" required placeholder="${esc(this.parent)}/my-project" value="${esc(this.draft.folder)}" ${busy}></label><label class="project-folder-choice"><input type="checkbox" name="createFolder" ${this.draft.createFolder?'checked':''} ${busy}> Create the folder if it's missing</label><div class="project-form-actions"><button type="submit" class="pa-new" ${buildDisabled}>${this.busy?'Building…':'Build home'}</button><button type="button" class="pa-ghost" data-cancel-project ${busy}>Cancel</button></div></form>`:'';
 this.host.innerHTML=`${actions}${importList}${form}${this.message?`<p role="status" class="project-status">${icon('info')}<span>${esc(this.message)}</span></p>`:'<p role="status" class="project-status" hidden></p>'}<div class="local-project-list">${homes.map(h=>`<div class="project-card"><button type="button" class="local-project-row" data-project-folder="${esc(h.project)}" title="${esc(h.project)}"><span class="project-tile">${icon('house')}</span><span><b>${esc(h.name||h.project.split('/').pop())}</b><small>${h.codexProjectId?'Codex project':'Observed folder'} · ${h.characters.length} resident${h.characters.length===1?'':'s'}</small><small class="project-path">${esc(h.project)}</small></span></button>${this.constructionMarkup(h)}<button type="button" class="project-remove" data-remove-project="${esc(h.project)}" aria-label="Remove ${esc(h.name||'project')} from Agent World" title="Remove this home from Agent World. Files and chats are preserved." ${busy}>${icon('trash')}</button></div>`).join('')||`<div class="empty">${this.townHallReady?'Build your first home. Choose an existing project or create a new one.':'Meet Mayor Martin and build the Town Hall first.'}</div>`}</div><small class="project-local-note">Local to this computer</small>`;
 this.updateConstruction();
 }
}
